### ISSUE TITLE
How to config 2 pushbuttons for one relay

### ISSUE THREAD

**Issue by eimix** [arendst/Sonoff-Tasmota#1012]
My goal is to use sonoff switches combined with wall switches.

Tried using SwitchMode1/SwitchMode2 with simple wall switch (togle button), but it is not so "self explaining" to home users if button is left in ON position and then light is turned OFF remotely with MQTT (OpenHAB2).

Is it possible to config sonoff basic with connected 2 pushbuttons?
![53126-5469567](https://user-images.githubusercontent.com/3492788/31482979-40c1b374-af33-11e7-99eb-3e0d47b54209.jpg)
(this image shows two keys(left/right) each with 2 pushbuttons (top/bottom))

Wanted action:
Top pushbutton always switch relay ON
Bottom pushbutton always switch relay OFF.

**Comment by ionciubotaru** [comment]
check the wiki for `switctopic` and `switcmode`

**Comment by eimix** [comment]
I checked it multiple times, found undocumented SwitchMode5/6 - but no success.

SwitchMode0
SwitchMode3
SwitchMode4
works with pushbuttons - but it always toggles relay if pressed multiple times.
In my case - i do not need to toggle relay, if "top" pushbutton is pressed twice or more. Relay must stay ON unless bottom pushbutton is pressed.

SwitchMode1
SwitchMode2
does not work with pushbuttons - as relay folows the state of pushbutton.

**Comment by davidelang** [comment]
On Thu, 12 Oct 2017, eimix wrote:

> SwitchMode1
> SwitchMode2
> does not work with pushbuttons - as relay folows the state of pushbutton.

This can work, you use your home automation software here instead of managing 
the relay directly.

you set switchtopic so that these send mqtt messages to your home automation 
server, and it ignores the contents of the message, you just have it watch for a 
message from button1, and when it gets one, it sends a message to turn relay1 
on. When it sees a message from button2, it sends a message to turn relay1 off

**Comment by eimix** [comment]
It looks like solution,
but it would not work if wifi network is lost or mqtt or openhab2 is down. 
it would be nice to have direct relay control.

**Comment by davidelang** [comment]
there's a limit to how many special cases can be put into the firmware, it's got 
a very limited amount of flash, and we are already at the point where we cannot 
update if all features are enabled due to this limit.

Is this worth loosing some other feature for?

Remember, you do have the source code, so you can add features that you want.

David Lang

**Comment by eimix** [comment]
I checked source,
found easy way to modify it for my self in sonoff.ino 
"switch (sysCfg.switchmode[i]) {"
with new switchmode7/8, but did not knew about "size" issue.

before any changes wanted to check, if this could be solved with config.

thank you for your tips.
