### ISSUE TITLE
Sonoff Dual setting module as "Dual" does not switch relays

### ISSUE THREAD

**Issue by peterforeman** [arendst/Sonoff-Tasmota#1179]
I've just installed a new Sonoff Dual as replacement for a Sonoff Basic. Now the fun part is: when configuring it as "dual" neither relays work. When configuring it as "Basic" (which it isn't) makes me switch Relay1 via the "Toggle" button on the webinterface.

Configuring it as 4CH actually does make me use the two relays. Help 😉

**Comment by chietanjain** [comment]
Are you using MQTT?

**Comment by peterforeman** [comment]
Yes, I'm using MQTT, but also that does not work when using POWER1/POWER2.

**Comment by flotre** [comment]
I have same issue.
Sonoff dual 5.9.1

Physical Relay don't work using mqtt, web interface, console.

And button don't work too.

**Comment by Tresett** [comment]
Are you disable serial port?

21 нояб. 2017 г. 2:24 AM пользователь "flotre" <notifications@github.com>
написал:

I have same issue.
Sonoff dual 5.9.1

Physical Relay don't work using mqtt, web interface, console.

And button don't work too.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arendst/Sonoff-Tasmota/issues/1179#issuecomment-345865201>,
or mute the thread

**Comment by flotre** [comment]
No, just configure firmware to sonoff dual

When configure as sonoff 4ch, it works.

**Comment by arendst** [comment]
Pls provide pictures and a link from where you bought it. This sounds to me like totally different hardware than the original dual using the serial interface to control two relays.

**Comment by saundersrg** [comment]
Having the same thing my side, LED changes, but relays don't kick over. Sonoff Dual Ver 2.0. SerialLog set to 0.

Chips to right of ESP8266EX are as follows from what I can see.

XTX
BN25F08
1(?)644Q0R

SIL
F330
B0GAZ
1624+

![img_5976](https://user-images.githubusercontent.com/34459499/33924499-ff9f57ca-dfde-11e7-86d2-fd8f127b7025.JPG)
![img_5977](https://user-images.githubusercontent.com/34459499/33924500-ffe7dd42-dfde-11e7-8916-d7c898079169.JPG)
![img_5978](https://user-images.githubusercontent.com/34459499/33924501-002e91e2-dfdf-11e7-8f07-c24cba64f941.JPG)
![img_5975](https://user-images.githubusercontent.com/34459499/33924502-006a9200-dfdf-11e7-83f2-78d83865a8b5.JPG)

**Comment by FuzzzzzyLogic** [comment]
Upgrading Tasmota from 5.9 to 5.10 fixed this for me, since it adds SONOFF_DUAL_R2.

- If updating in user_config.h, after flashing you may need to use the web interface to do `Console->"Reset 2"` to clear any stored override.
- Otherwise, you can update this in the web interface with `Configuration->Configure Module` and select `Module Type "39 Sonoff Dual R2"`.

**Comment by peterforeman** [comment]
Problem is solved for me using the 39 Sonoff Dual R2, closing.
