### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by jkiape** [arendst/Sonoff-Tasmota#156]
Trying to gain remote access to sonoff I made a port forward to sonoff's local ip port 80.
When I am trying to connect from outside, the web server redirects to local ip. 
Any ideas ?

**Comment by jkiape** [comment]
- [ ]

**Comment by legotheboss** [comment]
I don't know if I would recommend this. If you want remote access, I would suggest using a public MQTT broker and conveying commands via that. Make sure you use strong credentials to prevent others from maliciously using your sonoff.

**Comment by jkiape** [comment]
I'm aware of this process and I can do it relatively safe through Raspeverry pi (and port  forward) that I have.

Thank's

**Comment by splodgemcroo** [comment]
I had the same problem, and tracked the issue down to the fact that the webserver component has a captive portal function (presumably to help with configuring the sonoff if it's in AP mode? not sure as I haven't used it in that way).

In order to disable redirecting to the local IP, i edited the webserver.ino file, found the captivePortal() function, and commented out the whole  if (!isIp(webServer->hostHeader())) block so that the function always returns false.

Hopefully I've explained that ok - let me know if not, and I'll try and elaborate.

**Comment by jkiape** [comment]
It works! 
Thank you very much

**Comment by arendst** [comment]
Could you make the below change on line 1358 in file webserver.ino and let me know if that solves your problem too?
From
```
  if (!isIp(webServer->hostHeader())) {

```
To
```
  if ((_httpflag == HTTP_MANAGER) && !isIp(webServer->hostHeader())) {
```

**Comment by arendst** [comment]
Could you check if changing line 1358 in file webserver.ino from
```
  if (!isIp(webServer->hostHeader())) {
```
to
```
  if ((_httpflag == HTTP_MANAGER) && !isIp(webServer->hostHeader())) {

```
also solves your problem please?

**Comment by jkiape** [comment]
>also solves your problem please?
Yes it does !

**Comment by gabryk91** [comment]
@arendst I'm also trying to connect to my tasmota from outside, I did all the necessary configuration on my router from an x port to port 80 of the tasmota, but I can't see the web server, I had searched in the webserver.ino for the suggested lines, but I can't find those (I guess they were changed in recent updates). Can you provide me some direction to solve this problem? I understand the warning about opening the tasmota to the outside world, but still I want to do it with all the precautions, thanks
