### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by ZoltXs** [arendst/Sonoff-Tasmota#1843]
Hello, I'm new and I need help, someone could tell me if there is any tutorial like connect sonoff to mqtt mosquito server on Mac OS, I installed tasmota firmware but I do not know how to connect mqtt mosquitto to sonoff switch basic.

**Comment by reloxx13** [comment]
heya,

maybe this will help you: https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Features

**Comment by ZoltXs** [comment]
thanks but I do not understand it 😢

**Comment by TLCary** [comment]
In a nutshell:  Install Tasmota on your Sonoff.   Give the button on the Sonoff 4 short presses to put it into Wifi Access Point Mode.  On your Mac instead of connecting to your normal WiFi access point, connect to the Sonoff device.  Point a web browser to 192.168.4.1  (which is a web server on the Sonoff device). From the menu Configure/Configure MQTT/  enter the address of your Mac in Hosts...  Push the button again and put your Mac back on your normal Wifi.

**Comment by ZoltXs** [comment]
and the user and password I have not configured any in mqtt server are there any defaults?

**Comment by TLCary** [comment]
No. If MQTT server isn’t configured to require login you don’t have to provide any at all, or use any user/password you like. Doesn’t matter.
