### ISSUE TITLE
Adding a PCF 8591 ADC/DAC  Support

### ISSUE THREAD

**Issue by tombartosz** [arendst/Sonoff-Tasmota#209]
Please consider adding  PCF 8591 ADC/DAC module support to this project. It would enable possibility to connect analog sensors.

**Comment by ionciubotaru** [comment]
I think that instead of adding different peripherals support is better to add user defined functions.
Add `user.ino` with the following empty functions:
```
void user_before_setup() {
// code to run before Tasmota's setup
}

void user_after_setup() {
// code to run after Tasmota's setup
}

void user_loop() {
// code to run inside loop
}

// other functions to allow to connect different peripherals
```

In this way the upgrade process will be easier for users who use their own code and in the same time allow other users to develop interfaces without affecting Tasmota's core

**Comment by arendst** [comment]
Sounds like espeasy...

**Comment by davidelang** [comment]
There is a fair bit of code (with lots of ifdef protection) that is conceptually just walking through the sensor data and calling the appropriate mqtt_present or web_present code.

The proposal that I had under #217 to make there be an array that contained function pointers into each sensor would allow us to simplify the main code (simple loop over the array functions without all the ifdefs and different names) while making it easier to add in user code like this

**Comment by khcnz** [comment]
Its been a while since i have had to worry about function pointers in c - but a quick refresher http://stackoverflow.com/questions/840501/how-do-function-pointers-in-c-work if i understand correctly what you are suggesting is we could basically define a "interface" for modules so they could all have an config() init() loop() webpresent() mqtt() etc

**Comment by tombartosz** [comment]
Of cource I'm still interested.

czw., 13 wrz 2018 o 14:23 Adrian Scillato <notifications@github.com>
napisał(a):

**Comment by ascillato** [comment]
Great, have you done any progress on making a driver for it?

**Comment by ascillato** [comment]
I'm just looking for someone that has this chip and wants to make a driver for Tasmota and also that this request don't get stale.

**Comment by ascillato2** [comment]
Hi,

As it is a good idea but there is nobody working on a driver for that chip, this issue is being closed.

If anyone is interested on this, just ask and we can reopen this issue. Thanks.

**Comment by jello1974** [comment]
It would be nice if someone will make a driver for this chip
