### ISSUE TITLE
sonoff basic JSN-SR04t

### ISSUE THREAD

**Issue by rey90** [arendst/Sonoff-Tasmota#2796]
Hello

i have bought an sonoff basic. flashed the newest tasmota and changed the moduletype to generic, because i wan´t to connect an SR04.

![grafik](https://user-images.githubusercontent.com/39483606/40300942-fbfea790-5cea-11e8-82d9-4a63c9730428.png)

After connecting the SR04 the sonoff is not booting - anyone an idea?

**Comment by wongnam** [comment]
make sure you have to disable SerialLog (SerialLog 0) if you use GPIO1 and GPIO3 for SR04

**Comment by wongnam** [comment]
No need to change the module to Generic.
note that: do not connect SR04 direct to Sonoff Basic that the echo signal output will damage the sonoff due to SR04 using 5V.

**Comment by rey90** [comment]
i have not connect the sr04 directly. i have bought JSN-sr04t which comes with an board and should also run with 3,3v. If i don´t change the module to generic , were should i connect the sr04? i will need 3,3v + tri + echo + gnd

**Comment by wongnam** [comment]
Sonoff Basic still have GPIO1 and GPIO3

sê wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Basic

![image](https://user-images.githubusercontent.com/36041520/40301953-d7af9bec-5d17-11e8-9ac8-98ceafa5279a.png)

**Comment by rey90** [comment]
sorry my mistake. changed the mode back and also find this settings. but the module is still not booting up

**Comment by Jason2866** [comment]
Does the module boot normal without the sensor?
If yes connect the sensor to gpio 1 and gpio 14.
Maybe the sensor iritates serial in at boot time....

**Comment by rey90** [comment]
ok thanks . i have connected the sensor to gpio1 and gpio 14 and now the module is booting . But the value shown is completly wrong. TRI and ECH are connected in the correct way. Is there any option to debug this?

**Comment by rey90** [comment]
ok thanks for this information - i have also found an article about problems with 3,3v. Could anyone quickly help me to find 5v on the sonoff basic.

**Comment by Jason2866** [comment]
Take a look here
https://www.itead.cc/wiki/Sonoff
You will find a schematic diagramm here

**Comment by reloxx13** [comment]
scrape this line on the board:
![inked2018-01-29 19 30 10_lixx](https://user-images.githubusercontent.com/14855001/40456607-9186e2ba-5ef2-11e8-80e7-d724198e4e2b.jpg)

turn the board over and solder a bridge like here:
![inkedsonoff_pir_4_li](https://user-images.githubusercontent.com/14855001/40456627-b1383dca-5ef2-11e8-9b9d-c63380a7711e.jpg)

solder in a pin to the hole you just soldered a bridge to.

more info:
![sonoff_pir_4](https://user-images.githubusercontent.com/14855001/40456638-bbfeae1a-5ef2-11e8-8111-5b9efd50f891.jpg)
![inked2018-01-29 19 29 42_lixxx](https://user-images.githubusercontent.com/14855001/40456663-dab74b96-5ef2-11e8-8947-0fc09de8ce14.jpg)

**Comment by wongnam** [comment]
@reloxx13 Beware, do not connect Echo output directly to the GPIO directly due to the voltage level is not compatible(5V vs 3.3V).

Possible way is using a zenner diode to cut voltages above 3.3V
![image](https://user-images.githubusercontent.com/36041520/40458729-cba14e92-5f27-11e8-9451-d639524279ae.png)

**Comment by rey90** [comment]
thanks for your help. i will test it

**Comment by rey90** [comment]
just an update from my site: i have tried to take out the 5V without success, but this is till my bad soldering skills - will go on

**Comment by ascillato2** [comment]
Hi,

Have you managed to solve your issue?

**Comment by ascillato2** [comment]
Hi

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks

**Comment by Solraven** [comment]
firstly thank you. 
with the info on this page and a few other sources i have installed tasmota on esp01, connected it to a sr04t using a logic level converter, with 5v source connected to the sr04t side. i had given up on this project a year or so ago, i was going to try teaching myself and started off with blink and got frustrated, i was thinking i did something wrong and thought i had fried all 3 of my esp01's. at this point, i honestly think i just could not get them to boot because i didnt jump vcc and ch_pd. and than when i tried to reflash it it would fail, probably forgot to wipe first. my father was ill, and i didnt have the time or patience. than my father passed, and this stuff got tossed in a box until now.

the distance on the webgui comes and goes, any ideas why? is there a way without rewriting to change the distance to be something else, possibly a percentage between two set values, or even inject an equation to get Gallons?

the goal is to mount it in a pvc pipe and put that down in a water tank, to measure water level. at this point i could use some direction on where to go with this. the goal is get the level on a daily basis with minimal effort. possibly displayed on an lcd, or being able to ask alexa for the level. 

 when i ran power up the hill to the tank i put a cat5e cable going to a small poe router that is hooked to my asus ac68r router. i was reading up on setting up merlin on the ac68r as im under the impression that would allow me to set up a mqtt broker. are there better solutions? i was playing around with wemo emulation but i read it doesn't support sensors in the forums, tho https://tasmota.github.io/docs/Alexa/ states specificaly that hue does not support sensors but does not say anything about wemo. can alexa get info from a mqtt broker to answer a query? could i get a graphical level by loading tasmota_display on a second module and attaching an lcd? would i only get a digital distance displayed? does a esp01 have the required ports to utilize an lcd?

any help is appreciated?
