### ISSUE TITLE
How to get State for Switch Topic?

### ISSUE THREAD

**Issue by prasad7676** [arendst/Sonoff-Tasmota#281]
I have Main topic is...sonoff
switchtopic is.....switch

how to get stat for switch topic ... i tried Status 10 but its always says Switch1 OFF

<img width="1434" alt="screen shot 2017-03-24 at 7 11 53 pm" src="https://cloud.githubusercontent.com/assets/12240044/24317539/03ca02d4-10c6-11e7-8c00-221d7f69b768.png">
<img width="331" alt="screen shot 2017-03-24 at 7 14 01 pm" src="https://cloud.githubusercontent.com/assets/12240044/24317542/0fab9d92-10c6-11e7-8707-d855f0b68261.png">

**Comment by davidelang** [comment]
stat/ happens when a relay is changed. Switches are not relays. You will get a 
cmnd/switch/power message not a status message

status 10 shows if the switch is open or closed at the time the status command 
is issued.

**Comment by davidelang** [comment]
did the answer above clarify things for you? or are you still having problems?

**Comment by prasad7676** [comment]
yes. i got it now...but i having issue to pair with hue bridge emulator. i tried many apps to pair but i can only see those accessories in those apps but cant pair with them.

**Comment by stefanbode** [comment]
As far as I know, the emulation works as a bridge. Therefore no pairing needed/possible. This makes is easy to integrate with ALEXA. Otherwise, you need a bridge to get it working. I have seen on another project, that they defined the sonoff as a regular Hue client and you need e.g. a running OpenHAB Hue bridge emulator to connect first and then can search with Alexa. Besides the limit of 16 bridges in a network, the current implementation is much more convenient

**Comment by davidelang** [comment]
the sonoff doesn't implement full hue emulation, it implements just enough for alexa and google home to find it.

**Comment by nunoronconcouto** [comment]
Hi!!

My google Assistant dont find my sonoff with hue emulation...
Anyone can help me??

Thanks
