### ISSUE TITLE
add effects for WS2812

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-Tasmota#285]
I found a code with some cool effect for WS2812, can it be implement into Tasmota?

https://github.com/bruhautomation/ESP-MQTT-Digital-LEDs

also I am thinking, will it possibile to add a page in webui than user may customize few effects, just upload the code to the page and assign command name, like effect 1?

**Comment by davidelang** [comment]
similar to #39 It would depend  on what's needed for these effects. The ws2812 modules need to have the data fed to them on an ongoing basis, and there isn't time to calculate it on the fly. So the complete sequence needs to be stored on the device. Since we are so tight on ram and flash, this could be a problem.

**Comment by davidelang** [comment]
how small is "real small", even a few Kb can be a dealbreaker

remember, we have no ability to change the hardware in these devices, so we 
can't upgrade the flash, that would take using a different device. There are a 
few devices that have more flash, but the default is to build for the small 
flash size (and we actually use less than half of that, so that we can do an OTA 
update)

I'm pretty sure that arendst would accept a PR that enabled this, as long as it 
was ifdef off by default and documented the size difference that it added. It 
could possibly require an ifdef test to make sure it was being built on a device 
with enough flash.

David Lang

**Comment by hamwong** [comment]
Sure, it is up to you and @arendst, I just feel ws2812 is a good add on but function is very limited. It will be nice to have a little bit more feature on it

**Comment by davidelang** [comment]
it's not up to me :-) I'm just assisting.

It's up to whoever writes/ports the code and arendst to decide if he will accept 
the code.

I'm just trying to help identify what would probably be needed to have it added.

**Comment by hamwong** [comment]
Ok. So I guess this would shounds like no. I'll close the case than

**Comment by davidelang** [comment]
It's not a no, it's a "I think it's unlikely that @arendst will do this" and an 
explination of how I think it could be done.

**Comment by davidelang** [comment]
This is a reasonably common request, so unless @arendst says that he wouldn't accept it, I'm going to leave it open as a reference for others asking similar questions

**Comment by ascillato2** [comment]
Duplicated issue. Closing.
