### ISSUE TITLE
BlitzWolf BW-SHP2 wiring

### ISSUE THREAD

**Issue by WladyX** [arendst/Sonoff-Tasmota#3234]
Hi, 
I saw some wiring schema for blitzwolf sp1 here: https://github.com/arendst/Sonoff-Tasmota/issues/2223
Is it the same for BlitzWolf BW-SHP2?
I want to order one, but I don't find much information about how to connect the pins in order to flash it.
Thank you very much for your support and for your nice firmware!

**Comment by arendst** [comment]
Yes as far as I know.

My Blitzwolf BW-SHP2 ordered from Banggood Canada is still waiting for release for transport so I can't confirm yet.

**Comment by WladyX** [comment]
Then how do you know it is supported? :))
Thanks, I ordered one also, it will take about 1-2month to get my hands on it, hopefully you will get yours first.

**Comment by wilfredsmit** [comment]
Issue can be closed. Answered in wikipage [BlitzWolf SHP2](https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWoIF-SHP2).

**Comment by WladyX** [comment]
cool, thank you very much!

**Comment by arendst** [comment]
Verified too.

**Comment by jobhh** [comment]
wilfredsmit made a small typo, wiki page: https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWolf-SHP2

**Comment by kovacsm** [comment]
Hi!

I have ordered a SHP2 from bangood, and it seems it is a new version v2.3, which use a new wifi adapter(?).
And because of this it has a different pins.
As far as i saw, it still uses BL0937 chip, so i think it could run tasmota firmware.
I'm just don't know how to wire it. 3.3V and GND is clear, but don't know the others.
I have attached some pictures, I hope You can help me! :)
![img_20181108_095638](https://user-images.githubusercontent.com/17452899/48193505-e5f62900-e34a-11e8-9157-f77098c4a09b.jpg)
![img_20181108_095649](https://user-images.githubusercontent.com/17452899/48193506-e5f62900-e34a-11e8-9c16-0c6daa21de10.jpg)
![img_20181108_095727](https://user-images.githubusercontent.com/17452899/48193507-e5f62900-e34a-11e8-93c4-3cfa45f21bca.jpg)
![img_20181108_112728](https://user-images.githubusercontent.com/17452899/48193509-e5f62900-e34a-11e8-8a5b-402272c26102.jpg)

**Comment by arendst** [comment]
See #4297 and latest development release.
