### ISSUE TITLE
Sonoff crashes Pi after compromised flash

### ISSUE THREAD

**Issue by roikris** [arendst/Sonoff-Tasmota#3549]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x] Hardware used : Pi3
- [ ] Provide the output of command ``status 0`` : no output in this case, no access to sonoff
```
STATUS 0 OUTPUT HERE
```

Need some help with Pi -Sonoff/Tasmota flashing. 
followed this guide: https://github.com/arendst/Sonoff-Tasmota/wiki/Flash-Sonoff-using-Raspberry-Pi , and after flashing the Sonoff with the sonoff.bin file, the link disconnected before i could configure the wifi.
Since, everytime i try to connect the sonoff (Pow model) to the pi via VNC(regular or flash mode), the pi crashes. 

- button usage doesn't work or at least no LED response for different combinations.
- trying to flash/install software again as i think it was compromised, but i can't get it into flash mode as iv'e most likely deleted the original software and the button/LED's don't respond.
-trying to connect directly to the pi(instead of through VNC) works only if the Sonoff is connected before startup, crashes pie if connects after startup.
-when i try "miniterm.py /dev/ttyS0 115200 -e" i get a continuous string of random signs, until i have to close the command line.

Any ideas? what should i do now?

**Comment by curzon01** [comment]
As you did not mentioned: Did you disconnect your Sonoff Pow from main power during all of the procedures? This is essential and dangerous to life if not!

**Comment by Frogmore42** [comment]
I am pretty sure there would have been some smoke and Sparks if the POW was connected to mains power while connected to the RPi.

Unless the esp8266 has been damaged, you can always get it into flash mode, since it has a non-erasable bootloader.

I would suggest using a USB serial adapter (not an FTDI one, CH340 seem to just work for most people) with a PC.  People seem to have greater difficulty with using an RPi.

**Comment by curzon01** [comment]
I'd liked to give them a solution with what they have - otherwise we should remove the [related wiki entry](https://github.com/arendst/Sonoff-Tasmota/wiki/Flash-Sonoff-using-Raspberry-Pi)

**Comment by Frogmore42** [comment]
I agree that it should be possible to use a RPi to do the flashing.  The problem is that since the RPi only has a single serial port, you have to configure it to not use it for it's output.  You then still have to do all the things that are necessary to power and flash the esp8266.  I am assuming that someone was, at least once, successful in doing this and the wiki entry is the proof of it.  But, it seems that it is not an easy task to replicate.  I have never tried it, so I don't know all the ways it can go wrong.

From the data provided in the report, it is pretty clear the flash of the esp8266 is not good and it needs to be flashed again.

@roikris didn't indicate how the esp8266 is powered.  The guide says to use the 3v3 out from RPi.  This link says the 3v3 has the same 50mA limit as the FTDI
https://www.element14.com/community/thread/19550/l/is-maximum-current-from-33v-pin-really-50ma?displayFullThread=true
But, it also says you can get away with using more.  I suspect that is why it is inconsistent.  In any event, it is not one of those things that is likely to just work for most people.

Like any MCU flashing it is incredibly hard if you don't provide it with enough current and don't have it in bootloader mode.  Usually, once you know how to provide proper power and the magic sequence for bootloader mode and the magic commands for flashing it is really easy.  Add on top of that the need to solder wires in some cases and it requires a level of knowledge and capability that many people don't have when they start.  With some effort and persistence, most can acquire the knowledge and capability and become successful.

**Comment by curzon01** [comment]
Disabling the single serial port is described in the wiki linked above - roikris wrote he/she did the steps from it.
Question is how a bad flashed ESP crashs a RPi? It might be that flash is also not good but I wouldn't exclude other possibilities - even crash of the RPi is unexplained.

**Comment by roikris** [comment]
Answering your questions - as the wiring diagram shows, the Sonoff is powered through the 3.3V of the Rpi. it might be that it's a current issue.

How do i get into bootloader mode? is there a command i can use through the pi to check whether the Sonoff is indeed in flash mode?

**Comment by curzon01** [comment]
see [Wiki - Bringing the Module in Flash Mode](https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation#bringing-the-module-in-flash-mode) - simply for Pow: hold down the Button during powering your device.

Command to see if you are in flash mode may be read out some info from your device, examples:
```
# Read MAC
esptool.py --port /dev/ttyUSB0 read_mac
#  Read Chip ID
esptool.py --port /dev/ttyUSB0 chip_id
# Read Flash ID
esptool.py --port /dev/ttyUSB0 flash_id
```

**Comment by bouchardh** [comment]
I used the guide specified in the original post for flashing Sonoff classic and touch.

The only thing I did different is that I had power connected to the Sonoff before applying power to the Raspberry Pi or it would reboot as I applied power to the Sonoff device.
Also, for step 7, configuring wireless, the Sonoff rebooted after each command.

Hope this helps.

**Comment by Frogmore42** [comment]
> The only thing I did different is that I had power connected to the Sonoff before applying power to the Raspberry Pi or it would reboot as I applied power to the Sonoff device.

That indicates it was the issue that I said.  The RPi is no more capable of supplying enough power to the esp8266 as the FTDI.  You can read that as you results will vary and you really should use a separate 3v3 regulated supply for powering the esp8266.

**Comment by bouchardh** [comment]
Agreed Frogmore42, but at 2 in the morning and no 3v3 volts PSU, it did the job.

> I'd liked to give them a solution with what they have - otherwise we should remove the related wiki entry

Another diagram depicting this setup with separate power supply might be in order instead of just removing the page.

**Comment by Frogmore42** [comment]
Yes, another diagram is probably a good idea to have.

I have improvised "solutions" to many problems.  It is necessary sometimes.  But, understanding the things that can go wrong is sometimes necessary.  I once used an axe to bang in a nail.  It worked, sort of.  But, later I cut myself on the blade as I was putting it away.  Not really sure how it happened as I am usually very careful with it.  But, even a momentary lapse of attention when moving something dangerous can be painful, or worse.

Using a RPi for flashing a Sonoff is unlikely to ever be dangerous (unless the Sonoff is plugged into mains) but it is likely to be frustrating.  Flashing a Sonoff is hard if you have never done it before, using a RPi to do it is probably no easier than using an FTDI (actually it's harder, since you have to deal with both the power constraint and the default use of the serial port).  Adding more information on how to do it correctly will allow more people to be successful.  Since you were successful, update the wiki with your results, ie power up the RPi with the Sonoff connected to power, while pressing the button for GPIO 0.  Using that method, it is possible it will work for more people.

**Comment by ascillato2** [comment]
Hi,

Have you managed to solve your issue?

**Comment by ascillato2** [comment]
Hi,

Please, share your results when you have time. Thanks.
