### ISSUE TITLE
Any Sonoff device compatible with a clamp on current meter such as STC-013

### ISSUE THREAD

**Issue by c3reeman** [arendst/Sonoff-Tasmota#3626]
Has anyone used or been able to use a clamp on current meter with any of the sonoff range ? 

such as...

https://www.aliexpress.com/item/THGS-YHDC-30A-SCT013-0-100A-Non-invasive-AC-New-Sensor-Split-Core-Current-Transformer-New/32735255457.html?spm=a2g0s.13010208.99999999.272.69863c00L9G8aK

Its intended use is to monitor the current pulled from a cellar sump pump, accuracy isnt important really its just to get an indication of pump on/off. I know the obvious answer to this maybe use a sonoff POW R2, i did this however it failed and the onboard switch went open circuit after only a month of service... so the very thing that was supposed to monitor sump pump failure is the very thing that caused the failure ! A non invasive current monitor would eliminate this happening.

**Comment by Frogmore42** [comment]
That only puts out 1V at 30A, so it would might need an amplifier depending on the load.  Or, you could put it into the analog input.  The NodeMCU boards have a built-in resistor divider to make full scale 3V3.  You would probably want to full-wave rectify the signal and put a capacitor on it to smooth it out.  This should give you an indication of the pump being on or not.

**Comment by pmknowles** [comment]
The PZEM-004T works well with Tasmota. If you buy the cheap ESP8266 relay board from the internet (the one with the sub-board parallel to the long edge). Flash it with Tasmota. Select Generic and choose PZEM Rx for Tx and PZEM Tx for Rx. You can then connect the PZEM to the pin header between the relay and power terminal blocks. Use a USB charger PSU or a 5V buck to connect to the power and it will be fine. You'll need to install into an adaptable box as there is live AC on the PZEM. The relay on the board won't work by the way.
The PZEM is fairly accurate and the CT is rated up to 100A. What current is the sump pump rated at?
There are two versions of CT (split and one piece). It goes aroubd the live wire only.
If you want any further information let me know.

**Comment by c3reeman** [comment]
Thanks for all the advice guys, I’ve got quite a few parts coming from aliexpress now including a nodemcu , wemo d1 mini and I’ve just added a PZEM-004T following your advice.

Could you be more specific about the esp board your refering to @pmknowles, Have I already baught it ??

Once again thanks for the help

**Comment by arendst** [comment]
I use a sonoff basic back to back with the PZEM-004T encased in the box available from itead.

**Comment by c3reeman** [comment]
Ah that’s just perfect, sale on over at aliexpress so Ive already got another 20 sonoff basic’s coming.

Now I know I can use a sonoff and simply select the pins I’m much more in my limited knowledge comfort zone 

Great work thankyou

**Comment by arendst** [comment]
Picture:

![img_20180829_095139](https://user-images.githubusercontent.com/11044339/44773785-b6b88400-ab71-11e8-839f-df7aaa070861.jpg)

**Comment by c3reeman** [comment]
Looks good and I’ve got some of them boxes spare as well, I’m almost good to go I’m just doing a bit more research now and one thing I’m struggling with is the gpios and where to connect to the sonoff basic, please could you give details of which pins you connected it to, And if you have one plugged in and handy could you be so kind as to post a picture of the configuration layout on tasmota web gui ?

I can’t thank you enough for all the help and the great work you have done with tasmota, my entire home automation system is now 90% tasmota I’ve just got a few unreliable z wave door sensors to swap with tasmota and that’s it

**Comment by arendst** [comment]
Tasmota config:

![image](https://user-images.githubusercontent.com/11044339/44774870-8aeacd80-ab74-11e8-9f2d-336a6b462a0f.png)

I also had to add a 1k resistor to the PZEM-004T to change the serial interface power need from 5V to 3V3. 

![img_20180829_102810](https://user-images.githubusercontent.com/11044339/44775634-5f68e280-ab76-11e8-8e78-f9f9bc5f4fbc.jpg)

The four colored wires are then connected to the Sonoff Basic header:
- 3V3 Red
- Rx Yellow
- Tx Green
- Gnd Grey

![image](https://user-images.githubusercontent.com/11044339/44775841-e453fc00-ab76-11e8-8146-d913f76b7ae6.png)

**Comment by c3reeman** [comment]
Absolutely brilliant thankyou, 
Looking forward to reviving the parts from China !

**Comment by arendst** [comment]
As I wanted to document this anyway I just made an entry in the wiki https://github.com/arendst/Sonoff-Tasmota/wiki/PZEM004T-Energy-Monitor

Feel free to update with your experience once build.

**Comment by pmknowles** [comment]
Here’s mine using an HW-655 – it works off 5V and does the 3.3V to 5V on board (the relay is inoperative). It’s mounted in a UK dual gang surface mounted box under the fusebox.
[cid:image003.jpg@01D43F96.2A3E0960]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by meingraham** [comment]
@arendst what is the difference between what you've built to monitor energy and say the POW or the S31? Is your device limited to a 10A load due to the use of the Sonoff Basic?

@pmknowles ditto. Also, other than the 5V input, what is the primary difference between the HW-655 and a Sonoff Basic?

Thanks.

P.S. Still looking for someone who's used a PZEM to monitor a clothes dryer's energy use that handles the higher amperage.

**Comment by pmknowles** [comment]
The PZEM-004T can handle up to 100A (measurement only it can’t switch current)

The HW-655 works at 5V but converts the serial to 3.3V. The PZEM-004T needs 5V on the serial connection (unless you modify with a resistor).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by arendst** [comment]
The advantage of the PZEM-004T is also that you can connect a load without using a relay. This can be done with a Pow or S31 but then you have to short the relay.

In my case it's a complete copy of a Pow as I also use the Basic relay. BTW the energy monitoring of the PZEM-004T looks to me better than the old Pow.

**Comment by meingraham** [comment]
@pmknowles @arendst 

Apologies for high density factor on my part ;-)

I THINK I get it now...

The Sonoff Basic or HW-655 is powered by appropriate means in order to run the "smarts". The relay on the unit is not (necessarily) used to control the load. In the case of my dryer use case, it would not be used.

The PZEM is powered by 5V and hooked up to the load to be monitored, It sends its "readings" via serial interface to the smart switch (Sonoff or HW-655). The the higher power draw is completely handled by the PZEM.

Did I get it?

Mike

**Comment by arendst** [comment]
Yep.

**Comment by meingraham** [comment]
@pmknowles 

In your previous post, since you replied via e-mail, the image you'd sent did not make it into this track. Can you post that photo?

Thanks.

Mike

**Comment by pmknowles** [comment]
![wp_20180829_12_31_06_pro](https://user-images.githubusercontent.com/37398451/44794689-e8950f00-aba0-11e8-95ab-5ea788eba686.jpg)
There you go

**Comment by meingraham** [comment]
@pmknowles  What's the part number on your 5V buck?

**Comment by pmknowles** [comment]
Here’s the eBay listing
https://www.ebay.co.uk/itm/5Pcs-700mA-AC-DC-5V-3-5W-Buck-Convert-Step-Down-Power-Supply-Module-F-Arduino-M/152339220336?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pmknowles** [comment]
Generally comes with the ESP-01S - 3rd option in the drop down here.
https://www.ebay.co.uk/itm/ESP8266-ESP-01-5V-WiFi-Relay-Module-Smart-Home-Remote-Control-Switch-Phone-APP/273151370013?hash=item3f9917231d:m:mp-XSN3bIY0sCytX0KlBEbg

**Comment by meingraham** [comment]
My HW-655 based PZEM-004T power monitor for my 240V US standard electric clothes dryer.
![034481009559](https://user-images.githubusercontent.com/34340210/50610462-123caa80-0ea1-11e9-9c52-e9ff7722b9a8.jpg)
![20181223_154016](https://user-images.githubusercontent.com/34340210/50610473-1668c800-0ea1-11e9-9af6-463a04c79692.jpg)
![20181223_170453](https://user-images.githubusercontent.com/34340210/50610479-19fc4f00-0ea1-11e9-8238-d46a93850a32.jpg)

**Comment by amitubale** [comment]
> My HW-655 based PZEM-004T power monitor for my 240V US standard electric clothes dryer.
> ![034481009559](https://user-images.githubusercontent.com/34340210/50610462-123caa80-0ea1-11e9-9c52-e9ff7722b9a8.jpg)
> ![20181223_154016](https://user-images.githubusercontent.com/34340210/50610473-1668c800-0ea1-11e9-9af6-463a04c79692.jpg)
> ![20181223_170453](https://user-images.githubusercontent.com/34340210/50610479-19fc4f00-0ea1-11e9-8238-d46a93850a32.jpg)

Hi - Thanks for the pictures. I am planning to use it for the 220V dryer too.

1. To confirm is this your wiring
---110v-----------------------------------------------------------------Line Dryer pin
---110v------------PZEM Line--------------between CT Coil----------Line Dryer Pin
---Neutral---------PZEM Neutral---------------------------------------Neutral Dryer Pin

2. Since you are using a 5v buck converter and the ESP8266 relay board, you skipped the 1K resistor on the PZEM board on the VCC OUT going to the esp8266 relay board.

3. The Blue enclosure - is that from Lowes or Home Depot ? OR you got it online ?

Thanks

**Comment by meingraham** [comment]
@amitubale 

1. Correct except I wouldn't state it as "between CT Coil" but "through CT Coil"
2. I have the 5V and GND out from the buck converter connected to the power input terminals of the HW-655. The  HW-655 has four separate pins for the serial interface. I use the 5V and GND pins on the serial pins as input to the PZEM serial interface along with the Rx/Tx pins. This is the same setup @pmknowles has in his device ([link](https://github.com/arendst/Sonoff-Tasmota/issues/3626#issuecomment-416976400)). I do not believe that a resistor is required.
3. I actually purchased mine at Home Depot. The interesting thing is that when I looked for the part that was on the label of the circuit box, I could only find it on the Lowes website. The Home Depot website didn't have it and I looked for it both with the part number as well as looking at all of the circuit boxes in its online catalog. It's not like they are discontinuing it as there were two or three boxes full of them at the my Home Depot store. My sense is that this is a pretty common part. It worked great to fit everything and the opening flap made it easy to get everything placed inside. BTW, everything is just hot glued in place.

Look at the [Shelly EM](https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/1904226953009993/) coming mid-March. Rated for 120 amps - more than enough. It would be a much easier way to do this. It would consolidate the three separate modules and reduce a lot of the wiring. Had I not already bought the parts and built mine the week before this was announced (!), I would probably go the [Shelly EM](https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/1904226953009993/) route.

Mike

**Comment by meingraham** [comment]
@amitubale 

1. Correct except I wouldn't state it as "between CT Coil" but "through CT Coil"
2. I have the 5V and GND out from the buck converter connected to the power input terminals of the HW-655. The  HW-655 has four separate pins for the serial interface. I use the 5V and GND pins on the serial pins as input to the PZEM serial interface along with the Rx/Tx pins. This is the same setup @pmknowles has in his device ([link](https://github.com/arendst/Sonoff-Tasmota/issues/3626#issuecomment-416976400)). I do not believe that a resistor is required.
3. I actually purchased mine at Home Depot. The interesting thing is that when I looked for the part that was on the label of the circuit box, I could only find it on the Lowes website. The Home Depot website didn't have it and I looked for it both with the part number as well as looking at all of the circuit boxes in its online catalog. It's not like they are discontinuing it as there were two or three boxes full of them at the my Home Depot store. My sense is that this is a pretty common part. It worked great to fit everything and the opening flap made it easy to get everything placed inside. BTW, everything is just hot glued in place.
4. You're right, I don't need the relay. In fact, to use the PZEM with the HW-655 means that the relay cannot be used (because the relay is intended to be controlled via serial commands). The HW-655 just made the serial interface simple and didn't require me having to deal with both 5V for the PZEM and 3.3V for the ESP device. The HW-655 took care of the 3.3V regulation for me.
5. I do not believe the PZEM supplies the 5V. I think the PZEM 5V is an input to which you have to provide power. In this post ([link](https://github.com/olehs/PZEM004T/wiki/Basic-Setup)) it has this statement "... the PZEM will return "-1" to everything unless it is connected to power on both sides. That means GND and 5V DC on the data side and 80V-260V AC on the measuring side." I take this to mean you have to provide power to the data side and the AC side is only measuring the AC power metrics. I have not looked at the PZEM circuitry, but this tells me that the AC supply is not used to supply the DC circuitry. I think the reasoning is that doing so would mean that doing that would draw power from the AC thus affecting the actual AC power measurements. In fact, you should take care to where you tap the Dryer's AC Line for the buck converter so that current draw is not registering through the CT Coil. Anyway, long way to say, the PZEM DC it's powered from the HW-655 or directly from the buck converter. But it's just simpler to take it from the HW-655 via the serial interface pins.

As an aside, take a look at [this Shelly device](https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/1904226953009993/) coming mid-March. Rated for 120 amps - more than enough. It would be a much easier way to do this. It would consolidate the three separate modules and reduce a lot of the wiring. Had I not already bought the parts and built mine the week before this was announced (!), I would probably go the [Shelly EM](https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/1904226953009993/) route.

Mike

**Comment by fragolinux** [comment]
> The advantage of the PZEM-004T is also that you can connect a load without using a relay. This can be done with a Pow or S31 but then you have to short the relay.
> 
> In my case it's a complete copy of a Pow as I also use the Basic relay. BTW the energy monitoring of the PZEM-004T looks to me better than the old Pow.

2 questions:

1. so you don't use the relay part at all? Or in case you're limited to a 10A load max of the relay, right?
2. don't you need to turn off serial debugging to use sonoff's rx and tx, or this is due only in case of using them as general gpios?

thanks

**Comment by ascillato** [comment]
1- a PZEM is another sensor. See the pictures. You don't need to connect it to any relay if you want.

2- when you select the gpios for the sensor as the tx and rx pins of the esp8266, Tasmota put seriallog to 0 automatically.

**Comment by pmknowles** [comment]
The HW-655 uses serial commands to control the relay. I don’t use the relay (but it may still work). Basically the HW-655 simplifies supplying the 3.3V to the ESP8266 and the 5V that the PZEM-004T needs.

Adrian has answered the serial question as I was typing this.

Regards

Phil K

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by fragolinux** [comment]
@ascillato @pmknowles  thanks both :)

**Comment by fragolinux** [comment]
@ascillato  @pmknowles   thanks both :)
about the relay part, the question was more about @arendst 's setup in that transparent box, it's not clear if the sonoff is just used as a wifi microprocessor to control the pzem output (with no output from the sonoff at all), that just fit in the CT and go away from the other part, or the load passes out from the sonoff AND through the ct... to be clear: the out part is alwasy powered and just metered by the sonoff, or it's only ON in base of the sonoff being ON? In 1st case, you can put loads more than 10A, in the latter you can't, for security

**Comment by DillonJ** [comment]
Hey guys - what is the reason for the 5V buck? When you connect a SONOFF basic and use it as designed, it provides its own 3V3 from the mains supply... what is wrong with using it this way? I believe it is not used here for example: https://github.com/arendst/Sonoff-Tasmota/wiki/PZEM004T-Energy-Monitor

**Comment by meingraham** [comment]
@ascillato - regarding the use of the HW-655 relay while also using the serial interface to receive energy data from the PZEM... just wanting to get clarification for my notes for the future...

When the Generic module is set up to use the Tx/Rx pins in "PZEM" mode, one can't also issue a POWER or a TOGGLE command; right? One has to control the relay by sending the appropriate string of bytes. And likewise, one has to keep track of the state of the relay oneself, etc. In other words, one cannot use the TASMOTA features for the relay simultaneously with using TASMOTA to capture energy data from the PZEM.

Please confirm.

Thanks.

**Comment by meingraham** [comment]
@DillonJ,

The @arendst & @fragolinux devices use the ESP8266 (Sonoff Basic & Wemos D1 respectively) output voltage (3.3V) and use a resistor on the PZEM to account for the voltage the PZEM expects on it's input (5V). Thus they do **not** require a the 5V buck converter.

In the device @pmknowles designed, which I copied, the HW-655 supplies 5V directly to the PZEM - no modification to the PZEM is required. The HW-655 also requires 5V. It handles the voltage regulation onboard to supply the 3.3V the ESP-01 requires. One doesn't need to make any modifications. Thus the buck converter supplies 5V which is what the HW-655 requires and, in turn, the HW-655 supplies 5V to the PZEM.

Mike

**Comment by ChienTing** [comment]
Will the new version of PZEM-004T (V3.0)
SonOff can't read the value completely
Does anyone know the reason?
Thanks in advance

**Comment by homeseer666** [comment]
A few questions:

My use case is quite simple: I want to know if my 30A Dryer (North american 240V) is running or not; No need to actualy measure the current variation just a plain "is it drawing current or not"

I can assemble Arendst solution above; however I am not sure if I am overcomplicating things unnecessarily and trying to see if I can do this in a non invasive way.

Isn't there a way to simply usa a split-core like below (30A-1V for instance)
And use the GPIO's on a Sonoff basic to check if there is voltage or not on the split core transformer? I know the GPIO's can detect open/closed circuits but can it detect small voltage (0-1V) and/or what could be added in order to do so (small relay or something else?).

https://www.aliexpress.com/item/33021205090.html?spm=a2g0o.productlist.0.0.724b59f7UmtA0w&algo_pvid=fbfb6fdd-3968-400d-9852-b863140b7d9e&algo_expid=fbfb6fdd-3968-400d-9852-b863140b7d9e-3&btsid=0ab6f82415891278831177918e1ebe&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

Also, basic question: can these split cores be put around the full cable (two hot 120V AC wires + neutral) or will they only work if wrapped around a single hot wire? I think it's the latest but want to confirm. Worst case I'll open the back of the dryer and pass it around one hot wire.

Last but not least: if all the above doesn't make sense I'll deploy Arendst solution but I am not 100% sure on the wiring; can you confirm this is accurate (assuming the 1K resistor is added):

![2020-05-10_135247f](https://user-images.githubusercontent.com/56667580/81506689-3646a200-92c6-11ea-826e-224f29752914.jpg)
or
[https://www.dropbox.com/t/0Jx4Ot7ZpfzUZnWH](url)
or
[https://www.dropbox.com/s/1be4wcncfn4fgay/2020-05-10_135247f.jpg?dl=0](url)

Thanks, hopefully this will help other people as well.

**Comment by pmknowles** [comment]
To be hones the best way is to use a PZEM-004T with the LC Technologies relay board.
ESP8266 works at 3.3V and the PZEM uses 5V as Mike and I did. The PZEM does all the calculations and doesn’t need calibration. The Relay board also cheaply does the level switching in a small form factor and can be powered by a standard 5VDC supply. The CT goes around the single live wire.

Regards

Phil K

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by homeseer666** [comment]
Thanks for the prompt reply.
Ok got it, I am willing to go with that design, 
However the provided links to components either don't work anymore or don't deliver to Canada.
here's what I found can you confirm if accurate?:

https://www.aliexpress.com/item/32811467108.html?spm=a2g0o.productlist.0.0.3c862ec4S6A24q&algo_pvid=95bd8c67-6632-4bbe-bcc0-fbbe217fccd2&algo_expid=95bd8c67-6632-4bbe-bcc0-fbbe217fccd2-42&btsid=0be3746c15891347012658009e4dd8&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

https://www.ebay.ca/itm/1pc-AC-DC-5V-700mA-3-5W-Power-Supply-Buck-Converter-Step-Down-Module-for-Arduino/183413473551?hash=item2ab44b810f:g:570AAOSwZf9bZAi5

https://www.aliexpress.com/item/4000852483683.html?spm=a2g0o.productlist.0.0.3aa67712sJdD5a&algo_pvid=f4e896d0-ed82-471a-91fc-094a7cda2fd0&algo_expid=f4e896d0-ed82-471a-91fc-094a7cda2fd0-6&btsid=0ab6f81615891376606762591e2f95&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

Also some additional questions:

1 - If I decide to go the Sonoff route, can you confirm my design above is OK? My assumptions is that Arendst modification enable us to use a direct serial/gnd/TX/RX connection between the Sonoff unit and PZEM, option 2 being to tap the 5V from the Voltage regulator as shown in the image here : https://tasmota.github.io/docs/PZEM-0XX/  ( 6th image )

2 - Reading above I understand that both the CT+120V feed to the PZEM are required to measure power and not just the CT ?
Therefore I cannot avoid the whole huge Male/Female connector bundle and just tap the Dryer wire directly in a non invasive way, even if I have access to individual wires at the back of the dryer behind the connector, right?

BTW the Shelly 3EM would be interesting but at 99Euros it's a bit steep for a simple ON/OFF Dryer monitor...

**Comment by pmknowles** [comment]
Oh heck forgot you have 3 phases to get 240V!. Actually you don’t think need to measure all three phases. You can just put the CT on one phase and use live and neutral (if available) or 1 phase and another. In my version I mounted the whole gubbins in a dual (UK) 13A socket outlet back box. In your case you may be able fit everything do something similar but with a socket outlet.
The links are right (eBay can be slightly quicker than AliExpress). The new PZEM-004T uses Modbus but it’s still useable. An alternative to the buck is a USB charger with the microUSB plug removed.
Another alternative is to do the installation at the fuse box if it’s a discrete circuit.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by homeseer666** [comment]
Thanks;  Just to be clear, can I use 120v from any source to feed the PZEM or does it absolutely have to come from the same circuit I am monitoring? If it doesnt I will build a self contained Box with a 120V power cord+CT clamp and will simply hook it to one of the 120V hots inside the dryer. Would that work?

PS: The usb charger would imply an additional external component; would rather use power from the Buck converter.

**Comment by pmknowles** [comment]
The input side is essentially a volt and current meter – it is passive. The CT input and AC input are electrically isolated as they are measuring totally different things. I spose you may get some strange readings for apparent power if you’re using different phases.

Regards

Phil K

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by homeseer666** [comment]
Ok will do some testing when I get the components and report back. 
If anyone else has experience with North american current/devices please chime in.
Again I don't want to overengineer this, only need to know if the dryer is pulling high current (working) or not (Idle).
Cheers,

**Comment by CarlosGS** [comment]
> can you confirm this is accurate (assuming the 1K resistor is added):
> 
> ![2020-05-10_135247f](https://user-images.githubusercontent.com/56667580/81506689-3646a200-92c6-11ea-826e-224f29752914.jpg)
> 
> Thanks, hopefully this will help other people as well.

# ^^^^^^^ Can confirm that this works perfectly! ^^^^^^

It helps a lot, thank you @homeseer666 :pray: 

**note that the 1k resistor looks like this in new SMD boards:** https://github.com/arendst/Tasmota/issues/6050#issuecomment-510130142

Also leaving this here, just in case others face the same problem:
![photo5870733863272166413](https://user-images.githubusercontent.com/1636266/89716200-5f50fe80-d9ab-11ea-852f-8d92c0730b0f.jpg)

**Comment by homeseer666** [comment]
Thanks fot the feedback @CarlosGS  !

Glad to hear the visual design helped... and worked =)

I actually just received (part of) my Aliexpress order from 3 months ago....
Will also deploy on my end.
The sonoff basic sounds like a good/simple solution but I also ordered the HW-655+buck converter based on the above thread.  
I havent received the HW-655 yet but will test both options.

Will also test using a separate 120v feed (from the same receptacle as the washer for instance) and just clamp the sensor to one of the phases on the dryer to see if it affects readings. I would prefer this option since I could make the monitoring device self contained with a smaller footprint (vs a bulky 240V bypass box). Easier to switch to another dryer/device if needed.

Will report back, cheers

**Comment by homeseer666** [comment]
For anyone interested, I finally had time to tackle this project;
requirements:

- ability to easily move the device around if needed or for testing purposes;
- nothing bulky (which typically doesn't fit behind a dryer) or that would require rewiring.

Therefore I decided to build the device as a stand alone sensing unit;

I tested both designs described above and they work perfectly (HW-655 and Sonoff Basic) thx to @arendst, @pmknowles , @meingraham ) 
However, I had no other use for a HW655/buck converter  laying around so decided to go that route (+ no mod required to the PZEM). Simply used a small project box.

![image](https://user-images.githubusercontent.com/56667580/104244310-27555800-5430-11eb-9465-f29c5f54eecb.png)
![image](https://user-images.githubusercontent.com/56667580/104244325-2f14fc80-5430-11eb-8be4-25e25807876a.png)

Seems like feeding the PZEM with a separate 120v circuit (vs using one "live" from the "sensed" 240v appliance circuit) wasn't tested above so I can confirm that it is working fine.
240v appliances use both sides of the split-phase so not sure if the 120v circuit location makes any difference (feel free to chime in) .

![image](https://user-images.githubusercontent.com/56667580/104244366-4522bd00-5430-11eb-8d59-e3cda75a8ee4.png)

The unit is just slighly bigger than a deck of cards so you just mount it to the back of the dryer and run the split core around one of the live wires. As I expected, my dryer has a small service panel so installation was a breeze.

![image](https://user-images.githubusercontent.com/56667580/104244554-a77bbd80-5430-11eb-8c97-c3078ce4b343.png)
![image](https://user-images.githubusercontent.com/56667580/104246243-a0a27a00-5433-11eb-9e4f-ac2380ce11b1.png)


Since north american houses are on split-phase, shown voltage is 120v which reflects one of the 2 live wires used for the split core; however since we are working with split-phase (and not "2" phases  https://theengineeringmindset.com/120-240v-split-phase-us-can/) , wattage and current seem to be accurate (I doubt my dryer pulls 5500watts. 2800 watts when the element is on makes sense). @meingraham, I guess your results are similar?

I'm not totally familiar with apparent/reactive power/factor, but I'm sure some data post processing should resolve any inaccuracies if the data is relevant to you. Not here as I  just needed to know if device is off/idle/working.

![image](https://user-images.githubusercontent.com/56667580/104245189-d3e40980-5431-11eb-908c-496097886878.png)

Hope this helps other North american DIYers.

Cheers,

**Comment by homeseer666** [comment]
Just built the Sonoff basic verison; works equally well with less components;
About 20$ for the Sonoff basic + PZEM + Split CT + enclosure and wires.

![2021-03-23 01 07 24](https://user-images.githubusercontent.com/56667580/115641262-b05d1480-a2e6-11eb-817c-fc9c1a125134.jpg)

**Comment by dajrekt** [comment]
Hi Guys, 
I red this thread as I'm going to measure some high voltage devices like cooker, water heater, dryer etc 

I'm going to go with pmknowles project so I would like to connect the clamp in the fuse box. I pretty much understand all PZEM wiring and what does what however not sure of a few things
1. Does the PZEM have to be power up with the same fuse/source of the measure device or can it be any source? I thought PZEM can handle up to 100A when using a clamp for measurement. Is it safe to power it up with the line where the load might be 30-40A? I suppose if it is a paraller connection the load is whatever PZEM takes even from the same fuse (FUSE box) ? If it is serial connection (extension lead) the load is whatever measure device takes? 

2. On the picture of pmknowles what's the cable size of live wire ? is it 1.5? What would be recommendation here?

3. I also notice some of you use sonoff basic for their project and made like an extension lead to control on/off . I'm I right as by doing it this way you can only use it for load up to 10A as Sonoff basic max load is 10A?

Sorry for probably lame questions but I'm not an electrician. I will call for one of to make wiring in the fuse box for sure . Just wanted to know how this should be connected before I call for anyone. 

Please let me know if you need any clarification of my thoughts as I understand it might not be very clear 

Anyway its a great project!
Thanks

**Comment by pmknowles** [comment]
Q1. I powered the ESP from the lighting circuit (5A fuse in the UK). I then used an inline 1A fuse from the incoming (100A) breaker to the PZEM.
Q2. The cables are 1.5mm2 but could be any size to match the fuse rating.
Q3. You could use a contactor if you want to switch on/off a higher current remotely – however I’ve replaced 1 PZEM with a Shelly1PM which will switch 16A. I run it in MQTT mode so don’t flash with Tasmota.

Hope that helps

Regards

Phil K

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by homeseer666** [comment]
assuming you are in North america and considering all options:

Q1: here not using the same source and so far it works perfectly ; I have 4 units built/deployed (Dryer, Water heater, Hot tub, 240V heater); See design below + above.

![image](https://user-images.githubusercontent.com/56667580/122836384-261e3600-d2c0-11eb-99b5-27dbbe1f0b27.png)

Q3: Correct,  as per design above, the relay is 10A and can be used as you like. 
The sonoff just handles data processing via GPIO and hands it off to Tasmota.

**Comment by dajrekt** [comment]
Q1. I powered the ESP from the lighting circuit (5A fuse in the UK). I then used an inline 1A fuse from the incoming (100A) breaker to the PZEM.  

I thought you use the same source for both as per your picture via buck for ESP

Why did you not use lightning circuit for PZEM as well? 
Does it need 1A fuse for PZEM? 
Would you have any diagram?


Q3. You could use a contactor if you want to switch on/off a higher current remotely – however I’ve replaced 1 PZEM with a Shelly1PM which will switch 16A. I run it in MQTT mode so don’t flash with Tasmota. Hope that helps Regards Phil K 

I use Sonoffs Pow 2 which also are 16A , they work great for media switching and measurement . To be honest I don't need to switch off the water heater or the dryer, it was only my curiosity :)

> assuming you are in North america and considering all options:

I'm in Ireland, 230V single phase for domestic If I'm not wrong

> Q1: here not using the same source and so far it works perfectly ; I have 4 units built/deployed (Dryer, Water heater, Hot tub, 240V heater); See design below + above.

Is the measurement accurate? 
I will try it for sure but for some equipment I think will be easier to connect it in the fuse box.
 
Forgive me if I write some rubbish's or asking for obvious things. I know very little in this area however I was able to install my Sonoff pows myself so I'm learning :)

Thanks for you replies guys

**Comment by pmknowles** [comment]
I originally used the same source but the 240V to 5V PSU went after a couple of years so I reconfigured so I didn't need to turn off the whole house electricity to change it in future - of course it hasn't failed since. Bear in mind mine is measuring supply to whole house not just an appliance so my use case may be different.
Accuracy is very good less than 1kWh difference to the meter over a month on average (usage is about 400kWh per month). Typically I change the counters to match the meter once a year and it's around 8- 10 kWh out. I used it to send monthly usage to electricity company using a rule in openHAB but now got a SMETS2 smart meter so it will be retired soon.

Regards

Phil K

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pmknowles** [comment]
I used a POW on my 3kW (13A) immersion heater. There was a strange smell one morning and the housing had melted. The POW was still working. It's now in a different housing on the dishwasher. The immersion now has a Shelly1PM with the temperature sensor adaptor.
Regards
Phil K

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dajrekt** [comment]
Thanks guys for your input

I have another question.  Seems I have everything connected and configured but I'm not getting any readings from PZEM. Mine is V3 , someone above mentioned the same. Is there any issue with V3 or is it something wrong with my setup? I checked multiply times how is PZEM connected with hw655 and all looks good to me. 5V-5V , TX-RX, RX-TX , GND- GND. Any idea? ESP shows 0 everywhere . 

Regards

**Comment by pmknowles** [comment]
Have you selected PZEM-016 for Rx? Needs to be that for V3 cos RS485.

Regards

Phil K

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by homeseer666** [comment]
![Screenshot_20210622-235302_Office](https://user-images.githubusercontent.com/56667580/123033095-29dfb480-d3b5-11eb-9e60-e290b7dca905.jpg)

**Comment by pmknowles** [comment]
I know I had an issue with V3 but I can't remember how I resolved it.

It may have been baud rates or something  but if it comes to me I'll let you know.

Regards

Phil K

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pmknowles** [comment]
Might have been setting the module address to 1

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dajrekt** [comment]
> Have you selected PZEM-016 for Rx? Needs to be that for V3 cos RS485. Regards Phil K 

I have . but mine is opposite. GPIO1 is RX and GPIO3 is TX and module type is Generic 18 I think.

**Comment by dajrekt** [comment]
> Might have been setting the module address to 1 

Do you mean change it to Sonoff basic? 
I haven't try it , thought it doesn't matter

**Comment by pmknowles** [comment]
No there’s a command to set the ModBus Address of the PZEM to 1 – it’s in the Power Measurement section of ommands


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dajrekt** [comment]
> ModBus Address of the PZEM to 1

is it this one
ModuleAddress 1 ?

**Comment by pmknowles** [comment]
Yes

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dajrekt** [comment]
> Yes 

thanks, I will check it when I'm back home, 


Is there a chance that I missed something and the HW-655 must be flashed with something as well?

**Comment by pmknowles** [comment]
No the HW-655 just acts as a serial voltage converter to the relay and pin header. It probably won’t work until the serial log is disabled on reboot. It may be interesting to connect an FTDI to the oins to see what Tasmota is sending out. It’s worth trying to swap Rx Tx as there has been some issues with incorrect screen prints.

Regards

Phil K

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dajrekt** [comment]
It has started working!
This is my config

![20210623_185927](https://user-images.githubusercontent.com/78508173/123169939-d1bab800-d471-11eb-8d2d-1be3aebd70af.jpg)

I also set the address of the modbus to 1 with this command in the console
ModuleAddress 1

This is comparison with Sonoff Pow R2
![20210623_180718 (1)](https://user-images.githubusercontent.com/78508173/123170152-16465380-d472-11eb-9724-4b2d83501d4b.jpg)

Now I need to build another two meters and call for electrician to mess with my fuse box :)

Thanks for your help!

**Comment by pmknowles** [comment]
Yes I just spotted you had Tx and Rx on wrong GPIOs

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by homeseer666** [comment]
Additonnal note: If access is easier, you can also use the split cores directly at the breaker box; 
Be careful to turn off main power or have an electrician do it.
