### ISSUE TITLE
Tasmota needs sound !!

### ISSUE THREAD

**Issue by gemu2015** [arendst/Sonoff-Tasmota#3628]
i created an MP3 driver for this extremely cheap MP3 Player => DFPlayer mini (<2 Euros, 3 watt audio)
3 commands:

MP3Play track     track =>1-N
MP3Volume volume  volume => 0-100
MP3Stop

you simply place any mp3 files on a micro sd card and can then play it
i use it for sensor alarms when e.g. air quality is too bad
and i want to use it for extending my haus alarm siren
you could even think of an alarm clock with different alarm sounds or even musik.

it consumes nearly no resources, needs only one pin (software uart transmit)

attached is the (tiny) driver file. simply add it to the project (currently uses fixed GPIO 16 as transmit)

[xdrv_98_mp3.ino.zip](https://github.com/arendst/Sonoff-Tasmota/files/2332006/xdrv_98_mp3.ino.zip)

**Comment by arendst** [comment]
Ordered one. Now where do I get the music from....

**Comment by mike2nl** [comment]
gemu2015 has optimized his mp3 driver 18 hours ago:
https://github.com/gemu2015/Sonoff-Tasmota/blob/display-drivers/sonoff/xdrv_98_mp3.ino

He has added some defines, changed the void for mp3 play and changed the beloning code for the defines.

Here the file: 
[xdrv_98_mp3.zip](https://github.com/arendst/Sonoff-Tasmota/files/2334782/xdrv_98_mp3.zip)

**Comment by mike2nl** [comment]
BTW:
- we need a 3.3K .. 10K resistor when we will work with RX and TX in both lines.
- in single mode is a 10K better before the RX pin from the player.
- or use a level shifter because the player won't play with 3.3VDC. Min is around 4.3VDC.
- direct connect can be risky (info from internet).

**Comment by mike2nl** [comment]
gemu2015:
strange because when i use 3,3 VDC i get these rare effect that the player stops after a second
and the blue LED goes off. I can be possible that my 3.3VDC regulator, see photo please, is
not 100% ok but it works with other 3.3VDC hardware. So then my player must be damaged.

The 3.3V is stable until 800mA that means that something must be wrong. Will see in it what's
going wrong. 
And yes with a 3.3VDC power supply you need no resistor (data sheet).

Thank's for your feedback.

**Comment by andrethomas** [comment]
> The 3.3V is stable until 800mA

That's 2.64 watts of power... in theory a 8 ohm speaker should not use more than 413mA @ 3.3V

**Comment by mike2nl** [comment]
@andrethomas
right but the voltage regulator closes at 380mA so far i have messaured.
With a second supply it works. It looks like that the 3.3V regulator is
damaged. Today i got a new one, used him and it works. That is strange
because i never used such high current >= 450mA. And from 5V to 3.3V
by 500mA makes ~0.9W. But the coling plate can 20W. So it must be the
regulator self.

So that voltage issue is ok now and had not a lot of time to work on some
software to test things. Hope i have some free time the next days.

arendst wrote: On to the software...
Possible he is faster again ;-).

**Comment by mike2nl** [comment]
If someone will use the mp3 player driver xdrv_98_mp3.ino he has to change one thing in that file.

I use Arduino IDE 1.8.5 (.6 is out).

i added this in the user_config.ino:
// -- MP3 player on GPIO 14 -----------------------
#define USE_MP3_PLAYER                          // Use the tiny mp3 player

And i added **#include <TasmotaSerial.h>** in the xdrv_98_mp3.ino file.
between:
#ifdef USE_MP3_PLAYER
TasmotaSerial *MP3Player;

So it must look like:
#ifdef USE_MP3_PLAYER
**#include <TasmotaSerial.h>**
TasmotaSerial *MP3Player;


Otherwise Arduino IDE's compiler will shoot out an error that the **MP3Player** has no type.

**Comment by mike2nl** [comment]
Right now i´m busy with the selectable GPIO pin. Software is changed and upload is running.
Will report back later...

**Comment by mike2nl** [comment]
Short Update:
- Added the english mp3 player text to all lanugae files.
- Copiled it again with A-IDE 1.8.5 and upload was ok.
- Tested now all 4 GPIO's which were selectable for the sonoff basic. All working.
- Next to test a rules. E.g. based on a time start playing BigBen.
For that i have to take a deep look to the rules page in the WiKi.

Next i want to test some more commands (e.g. Play Next, Play All, Folder, ...)
Have studied the data sheet i have from the original source and will 
do some tests to get a feedback. Some little tests but the free time is 
small at this time of the year.

**Question to all of you:**
Is this something of interest or do you say: "no the three commands are enough".
Then i will do it in two parts and the advanced part later for me or the one who wish to have it.
Possible is configuration too in the user_config.h with simple/ default & /advanced

Please some feedback...

**Comment by ascillato** [comment]
Cool!

Very nice indeed. I like it! :+1: 

You can make a PR with just the basic commands when you have it working and then, when you have the rest, you can make another PR to add more features.

That only depends on your time and how it is easier for you. The space difference between 3 commands and 6 (for example) should be very little. So It does not make the difference for the overall project. 

When you make the PR, please add the line `//#define USE_MP3_PLAYER // Use the tiny mp3 player` to user_config.h file as commented out in order to keep the flash size low for the versions that do not require this feature.

**Comment by mike2nl** [comment]
@ascillato 
Thanks for the kind words. 
Additonal i have cleaned up the original xdrv_98 code a little bit for better and faster reading. 
Will rename it to xdrv_91 because i have seen so much 96, 97 and 98 stuff.
I hope i get it done at the  while(weekend) {...};

**Comment by mike2nl** [comment]
After merging needs testing. Will do the test today or tomorrow.
Then report back and when that is ok we can close the issue, i think.

**Comment by mike2nl** [comment]
so have doen some rule tests under Version":"6.2.0.2". My merge request version.
Have to do the same with the latest version.

Rule Test 1:
rule1 on Time#Minute do mp3play 001 endon = worked every minute
- After 10 seconds i typed mp3stop.

Rule Test 2:
rule1 on Time#Minute do backlog mp3play 001; ruletimer1 10 endon on rules#timer=1 do mp3stop endon = worked every minute
- But sometimes it looks that the mp3stop command after 10 seconds is to fast,
because he doe'nt stopped. Have to do the same with the latest version and a
timer value of 15, 20, 25 and son the see where it hangs. It can be the code too.
When this is not differnet than now i will chnage the if and else if inot a state 
machine switch() it's faster and mnore secure. Also better for the next stage of
development.

**Comment by dr-apple** [comment]
I don't understand how to connect rx and tx from the DFPlayer to the esp8266 ?

**Comment by ascillato** [comment]
We should add all this information to the wiki

**Comment by ascillato** [comment]
Commands added to the wiki: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#dfplayer-mini-mp3-player

**Comment by ascillato2** [comment]
Closing issue as DFPlayer mini has been implemented in Tasmota.

Thanks @mike2nl, @gemu2015, @arendst

**Comment by Jason2866** [comment]
Hello @mike2nl 
i get this compile error in VSC when i enable it via #define USE_MP3_PLAYER

Compiling .pioenvs\sonoff\lib29e\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
D:/Sonoff-Tasmota-development.6.2.1.3/sonoff/xdrv_14_mp3.ino: In function 'void MP3PlayerInit()':
D:/Sonoff-Tasmota-development.6.2.1.3/sonoff/xdrv_14_mp3.ino:112:29: error: 'MP3_VOLUME' was not declared in this scope
MP3_CMD(MP3_CMD_VOLUME, MP3_VOLUME);            // set volume depending on the entry in the user_config.h
^
Compiling .pioenvs\sonoff\lib29e\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pioenvs\sonoff\lib29e\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pioenvs\sonoff\lib29e\ESP8266WiFi\WiFiClientSecure.cpp.o
*** [.pioenvs\sonoff\src\sonoff.ino.cpp.o] Error 1

**Comment by mike2nl** [comment]
@Jason2866
in the user_config you will find the following at line 345 & 346:
//#define USE_MP3_PLAYER                           // Use of the DFPlayer Mini MP3 Player RB-DFR-562 commands: play, volume and stop
  #define MP3_VOLUME           10                // Set the startup volume on init, the range can be 0..30(max)

To use the mp3 player delete the two '//', but i think you know that ;-).
MP3_VOLUME 10 - is declared so far i see.
You have the latest version?
- I will do a compile test right now.

**Comment by Jason2866** [comment]
@mike2nl 
Had a problem with VSC....  Compiles without a problem.
Thx

**Comment by kinghill44** [comment]
Hello,

Nice Plugin. Is it possible to include the Commands Next/Prev Song to Tasmota Firmware?

THX

**Comment by ascillato2** [comment]
Copied request from @AUyttendaele in #5039 :

Hi the MP3Player is working fine but is lacking commands to be truly functional

Addition of Following basic commands would be great
NEXT_SONG | 0x01 | Play next song.
PREV_SONG | 0x02 | Play previous song.
SHUFFLE_PLAY | 0x18 | Playback shuffle mode. Data is 0 to enable, 1 to disable.

These would allow a basic MP3 player functionality.

The Folder commands would be nice but are not of the same importance.
PLAY_FOLDER_FILE | 0x0f | Play the file with the specified folder and index number
SHUFFLE_FOLDER | 0x28 | Playback shuffle mode for folder specified. Data high byte is the folder index.

Thanks

**Comment by eggfat** [comment]
Hi there, Im trying to install this onto a d1 mini but Im having no luck. Does the DFPlayer have to be wired to the d1 using a board to install the firmware ? 
Many thanks for any help. 
Here are the errors I'm getting.
arduino.ar(core_esp8266_main.cpp.o):(.text._ZL12loop_wrapperv+0x4): undefined reference to `setup'
arduino.ar(core_esp8266_main.cpp.o):(.text._ZL12loop_wrapperv+0x8): undefined reference to `loop'
arduino.ar(core_esp8266_main.cpp.o): In function `loop_wrapper':
/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/cores/esp8266/core_esp8266_main.cpp:111: undefined reference to `setup'
/Users/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.1/cores/esp8266/core_esp8266_main.cpp:111: undefined reference to `loop'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board WeMos D1 R2 & mini.

**Comment by ascillato** [comment]
Hi,

Your are having a compilation issue not related to DFPlayer. Please, address your issue to the Tasmota Support Chat. Thanks

**Comment by TheBurgundyBear** [comment]
> Commands added to the wiki: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#dfplayer-mini-mp3-player

Hello! It appears this Wiki page does not exist anymore? I'm attempting to get my DFPlayer working after having issues with ESPHome and firewalls. Any assistance with how to set up the DFPlayer with Tasmota is appreciated!

**Comment by meingraham** [comment]
Documentation was moved several months ago. Older issues unfortunately will still refer to the older links.

Please visit [tasmota.com](https://tasmota.github.io/docs/Commands/#mp3-player)

**Comment by TheBurgundyBear** [comment]
> Documentation was moved several months ago. Older issues unfortunately will still refer to the older links.
> 
> Please visit [tasmota.com](https://tasmota.github.io/docs/Commands/#mp3-player)

Nice! Thank you! However, what I'm specifically looking for is a template or something to get the DFPlayer to work and I haven't come across that yet. I see the commands at that link, but nothing else.

**Comment by meingraham** [comment]
Like most peripherals, you have to connect it to a free GPIO and configure Tasmota with the appropriate component (i.e., `100 - MP3_DFR562`). There is no pre-made template because practically any ESP device can be used to attach the supported MP3 player peripheral (DFR562). You will have to configure your device accordingly. I don't believe that the MP3 driver is pre-compiled into any of the Tasmota variants. You will have to compile your own binary with `USE_MP3_PLAYER` defined.

**Comment by TheBurgundyBear** [comment]
> Like most peripherals, you have to connect it to a free GPIO and configure Tasmota with the appropriate component (i.e., `100 - MP3_DFR562`)...

Thank you once again, @meingraham. It does appear that the driver is included in the sensors binary:

![image](https://user-images.githubusercontent.com/60525926/84594091-dfc90800-ae1d-11ea-8926-f4efd55cef47.png)

So you're saying all I need to do is hook up a free GPIO PIN? When using ESPHome, I had it hooked up to TX and RX on a NodeMCU.

**Comment by meingraham** [comment]
Yes, it requires Rx/Tx.

You define the additional component on a free GPIO so Tasmota knows you have that peripheral connected and uses the driver for the correct protocol for the DFPlayer Mini. It's not an actual physical connection.

I have not used this module so I can't provide much more information. If you have further questions, I recommend you visit Tasmota's Discord.

**Comment by TheBurgundyBear** [comment]
> Yes, it requires Rx/Tx...

Yeah, unfortunately the console is saying "Command Unknown." Do you happen to have a link to the Discord? The hyperlink located here: https://tasmota.github.io/docs/FAQ/ is linking to http://thehackbox.org/tasmota/release/

And for some reason Google isn't yielding anything either! Starting to wonder if I'm having DNS issues... this is weird.

**Comment by meingraham** [comment]
Yeah, that link appears to be wrong. It's not your DNS.

The support forums links are also at the bottom of the docs homepage.

https://discord.gg/Ks2Kzd4

**Comment by TheBurgundyBear** [comment]
> Yeah, that link appears to be wrong. It's not your DNS...

Thanks so much for the help, @meingraham! I'm into the Discord now! The troubleshooting continues...

**Comment by saschaludwig** [comment]
> Commands added to the wiki: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#dfplayer-mini-mp3-player

The link is invalid :-(

**Comment by ascillato** [comment]
Docs have been moved to tasmota.com

**Comment by brjhaverkamp** [comment]
Was reading on this mp3 player solution. Sounds interesting. But looking for more information, I just noticed that it isn't listed in the supported devices page. At least I couldn't find it there.

**Comment by meingraham** [comment]
https://tasmota.github.io/docs/Commands/#mp3-player

**Comment by brjhaverkamp** [comment]
Hi Miengraham,

Indeed, there is the information on the Commands in that section. But the device itself is not listed in the offical 
supported devices list: https://templates.blakadder.com/
(linked via https://tasmota.github.io/docs/devices/)
I was looking for a tasmota enabled music player, but couldn't find one on that list. I stumbled upon the commands and the reference to the DFPlayer mini more or less by chance.

**Comment by meingraham** [comment]
@brjhaverkamp 

Both the templates site and the Tasmota docs are open. Your contributions are welcomed.
