### ISSUE TITLE
ruletimer stop

### ISSUE THREAD

**Issue by benzino77** [arendst/Sonoff-Tasmota#3633]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
Let's say there is a configuration:
```
rule1 
on event#R0 do 
   backlog ruletimer1 %value%;
   sensor29 0,on 
endon
on rules#timer=1 do 
   sensor29 0,off 
endon
```
now when I fire `event R0=120`, timer will do his job and change the state of MCP230XX pin 0 to off after `120` seconds.
When I stop/clear the timer by `ruletimer1 0`, the event `rules#timer=1` will not fire. It could be nice to have this option (it doesn't have to be `ruletimer1 0` it can be `ruletimer1 off` or `ruletimer1 stop`) 

**Describe alternatives you've considered**
do 
`backlog sensor29 0,off;ruletimer1 0;` 
but `ruletimer1 0/stop/off`, firing event would be more elegant (i think) especially when there is a lot of stuff to do on event `rules#timer1`

**Additional context**
No needed.

**(Please, remember to close the issue when the problem has been addressed)**
Ok.

**Comment by ascillato2** [comment]
Hi,

Thanks for sharing your ideas.

But Sorry. Would be very confusing that when you run `ruletimer1 0` make it fire itself. It is designed to be a cancel feature. Please, consider change your rules and perhaps add another rule for making it fire as you want.

```
rule1 
on event#R0 do 
   backlog ruletimer1 %value%;
   sensor29 0,on 
endon
on rules#timer=1 do 
   event stop_my_stuff
endon
on event#stop_my_stuff
  backlog ruletimer1 0;
  sensor29 0,off
endon
```

So, instead of `ruletimer1 0` to make it fire, you can use `event do_my_stuff`

Hope this helps.
