### ISSUE TITLE
Error when compiling 6.1.1 in xdrv_06_snfbridge.ino

### ISSUE THREAD

**Issue by nibbsification** [arendst/Sonoff-Tasmota#3639]
**Describe the bug**
When I try to compile the sonoff.ino, ardino is failing with an error message on line 112: 
`too many arguments to function 'uint8_t ihx_decode(uint8_t*)'`

- [X] _Searched the problem in issues and in the wiki_

**To Reproduce**
_Steps to reproduce the behavior:_
Loding the project into the IDE and check/compile

**Expected behavior**
Project compiles

**Additional context**
_Arduino IDE 1.8.6_

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Sorry. Can't reproduce. Current codebase is compiling just fine. [![Build Status](https://img.shields.io/travis/arendst/Sonoff-Tasmota.svg)](https://travis-ci.org/arendst/Sonoff-Tasmota)

Please, uninstall and install again your Arduino, esp8266 libraries, tasmota libraries and Tasmota files as explained in the wiki.

Also, please, search in issues because this type of problems has been addressed several times and there you have a lot of troubleshooting.

Thanks
