### ISSUE TITLE
character "*" dont't work in Wifi password entered via Webgui

### ISSUE THREAD

**Issue by Karl-opec** [arendst/Sonoff-Tasmota#3654]
**Describe the bug**
See Title. when these characters are used for Wifi password via user_config.h they work

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ x] _Searched the problem in issues and in the wiki_
- [ x] _Hardware used_ :  sonoff basic

**To Reproduce**
Enter a wifi password with these Character the connecting to the AP fails with "invalid Password"
on the serial console

**Expected behavior**
it should be possible to use these characters in the Webgui

**Comment by Frogmore42** [comment]
Probably best to avoid those characters, unless you are a tester for Wi-Fi compliance 😀.

**Comment by ascillato** [comment]
Yes, sorry. Those characters are not supported.

**Comment by ascillato2** [comment]
Hi, sorry. Those are not supported by now.

**Comment by arendst** [comment]
Investigating.

**Comment by ascillato** [comment]
Hi, @arendst, I was thinking to make Tasmota not to show the * in the password fields on the UI and leave it blank. So, if the user add something there, the password will change. If nothing is added, the password will be left unchanged.

What do you think?

**Comment by ascillato** [comment]
The $ symbol works fine. The issue is only with *

**Comment by arendst** [comment]
How do you want to let the user add a blank password?

Currently an empty field returns a blank password. If there are no asterixes it will show the default text of "APx Password".

**Comment by ascillato** [comment]
Yes, you are right.

We can leave as it is right now and specify that the symbol * is not supported in a password

**Comment by arendst** [comment]
I'm afraid it has to be that way. I made some changes to the debug code to let me see the passwords on request.

If you enter a password in the gui between quotes like "I$Know*It" the password is recognized as I$Know*It so that way it works as expected.

It's probably an anomaly with HTML input fields with type password as the normal console input field does recognize the command ``password I$Know*It`` correctly...

**Comment by localhost61** [comment]
> If you enter a password in the gui between quotes like "I$Know*It" the password is recognized as I$Know*It so that way it works as expected.
Good to learn there is a workaround but I unfortunately it didn't help me today...

Actually on 6.3.0.15, using the URL command line, I wanted to normalize the Hostname of my 6 Dual R2 in production as Roller shutters. Something like : `http://192.168.144.125/wi?h=Dual_05&save=`
I took less than 1 minute to do that this way for all of them, but what a carnage !!!
Even if my passphrase was not mentioned in the URL, it was retrieved and as it contains a star character, because of this issue the Sonoffs couldn't reconnect, they were all blinking :-/ (Christmas before time !)
Not to mention I had to reset all the configs, using a stepladder to reach them and pushing the main button during 40s :-( ...
Not to mention that the config backups I had were outdated for half of them (v6.0.0) and throw an exception when restored... 
I chance I was not obliged to unmount them and reflash on USB.

My punishment to have a star in the passphrase, but I guess that entering an erroneous one would result in the same. Isn't it? That make me think that it would be a good practice to fill the 2nd AP settings with those of my smartphone, that I would activate to workaround those situations.
