### ISSUE TITLE
Help to configre Basic sonoff with two windows senores 

### ISSUE THREAD

**Issue by aihysp** [arendst/Sonoff-Tasmota#3801]
Hi i would like to config two windows sensors on the basic 

i was thinking about using GPIO 0,14

can anyone tell me if this is the right way to do that?
what config should I use for 
switchMode
switchTopic
buttuntopic

any ideas well be welcomed thanks!

**Comment by andrethomas** [comment]
Have you considered reading [this](https://github.com/arendst/Sonoff-Tasmota/wiki)

**Comment by Frogmore42** [comment]
Yes, while it can sometimes be hard to find what you want the wiki does have lots of good information about your questions as do many of the other issues.

GPIO 0 is a bad choice for an input switch, as stated in the wiki and other issues because it can render your device inoperable if the switch is closed during a power failure.

**Comment by ascillato2** [comment]
Hi,

Closing issue as it has been answered. Please, ask to reopen if needed. Thanks.

**Comment by aihysp** [comment]
ascillato2 you are fast :)

one more Q...
can i use other GPIOs? 3,1,4?
do i need to put some kind of resistor?

**Comment by andrethomas** [comment]
Yes you can use other GPIO - experiment with it a little to learn for yourself.
