### ISSUE TITLE
Analog in mode in module config

### ISSUE THREAD

**Issue by Amli2011** [arendst/Sonoff-Tasmota#3831]
Refering to Issue #137. It is there stated that setting the mode of the ADC is impossible from inside setup() or loop(). Only possible from a #define statment before compiling. This is only almost true. LUA has an function to (more) dynamicaly change the setting, only requiring a reboot afterwards.

LUA is using a function named: force_init_mode, internaly translating to adc_init107 (changing the init byte 107 witch contains the ADC input select, if I understands it correctly)

Here is a link to LUAs implementation:
https://github.com/nodemcu/nodemcu-firmware/blob/8181c3be7aed9f0a0ceb73ac8137c1a519e8a8e9/app/modules/adc.c

Could it be possible to implement this in Tasmota? To get it easy to config along the other module/pin configs. It will also make updating the modules more easy as it will not longer need to be compiled for the module that uses the A0 pin. A pre compiled .bin will work.

This is a little more than my copy and paste programming could handle, but I think someone with a bit more skills than me easy could figure this out.

Thank you all for the incredible versatile software!

**Comment by ascillato** [comment]
Sorry,

That issue is closed and very old (mar 2017).

The analog input is already implemented in Tasmota to read the A0 pin. No need to add any code.

Just use the sonoff-sensors.bin from http://thehackbox.org/tasmota/sonoff-sensors.bin

Thanks.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
