### ISSUE TITLE
How to connect MC-38 door sensor to Tasmotized Wemos D1 mini

### ISSUE THREAD

**Issue by tlpbu** [arendst/Sonoff-Tasmota#3915]
Please help me to connect [MC-38 magnetic door sensor](http://blogmasterwalkershop.com.br/arquivos/datasheet/Datasheet%20MC-38.pdf) (actually 2 of them) to Wemos D1 mini flashed with Tasmota v.6.1.1.

To my understanding it should be same as ordinary wall switch but I somehow could not make it work to publish state messages via MQTT.

**Comment by ascillato2** [comment]
Hi,

A lot of information is missing in order to properly help you.

Please, complete the troubleshooting template. Use the command GPIO in order to see HOW it is connected. Use the command weblog 4 and show the output of the console when you try to use it. Explicit what switchmode and switchtopic are you using. If using rules, which ones.

**Comment by tlpbu** [comment]
@ascillato2 I did not provide all the data you asked because the was no particular issue with with Wemos devices or Tasmota. I was hoping for some tutorial for connecting MC-38 door sensors because to my surprise there is literary zero as far as google search can find.

Meanwhile I managed to set up everything the way I wanted usng Tasmota rules you hinted. 
Initial problem was that both sensors were reporting to same stat/.. topic but I could fix that with rules. Now each sensor reports to own MQtt topic so Home Assistant could monitor each door state via MQTT binary sensors.
