### ISSUE TITLE
Sonoff T1 3ch gpio2 issue

### ISSUE THREAD

**Issue by gazzaman2k** [arendst/Sonoff-Tasmota#3994]
ive ready the wiki what im trying to do is add a reed switch to gpio2 on a 3 channel t1 uk switch.

so ive gone into the configuration and set gpio02 to switch 4, 5, 6, 7, 8 no matter what one its on when i close the reed switch (or just jump the wires together) it turns on button 1 and its relay.....

is there some setting that makes gpio2 or switch 4, 5, 6, 7, 8 link to the button 1/relay 1 combo????

its the old version t1 with the connections on the bottom not the newer one where they are either side.

anyone added any extra sensor/relay or button / switch to a t1 3ch before?

thanks

**Comment by ascillato** [comment]
Hi,

Sorry that you didn't search in the issues, nor in the wiki. There are lots of examples about this.

You need to configure your GPIO where you have the reed switch in order to not control relay 1 as you want.

You need to set a rule to catch your reed status and to send a MQTT message.

Choose a GPIO as explained in the wiki at: https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs

Configure the GPIO you have your reed connected as for example switch4. Then, go to the console and type:

```
rule1 1
rule1 on switch4#state do publish cmnd/sonofftopic/reed %value% endon
```

For further information, please follow the troubleshooting template, search in issues, search in the wiki and ask in the Tasmota Discord Chat. Thanks.
