### ISSUE TITLE
How to automate testing in TASMOTA?

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#4018]
Hi Theo, 

how did you manage it to make so many changes in this short of time with this small amount of bugs? The code quality is remarkable. Do you have automated testing of functions? If yes, please can you give a small insight into how you do it, because I ran into a similar situation with my MOD. There are sometimes side-effects by code changes in the master, that break my functionality without getting noticed by me upfront. Testing everything manually is also for my small additional at this point very annoying. Thanks for sharing.

**Comment by digiblur** [comment]
He's not human...  I have the same thoughts digging under the hood.  Truly impressive tight code!

**Comment by arendst** [comment]
I'm human and have no automatic testing. I eat, drink and live Tasmota with some quality time in between. I think I know what happens if I tweak something here then it probably has impact there. I know it doesn't sound professional but as long as I manage to keep acquainted with my changes I keep the overall picture. More often I seem to forget an impact but then users luckily notice it and I jump on a solution.

It gets difficult with user provided PR's. For some sensors I stopped learning there intricacies and totally rely on the guy/gal who provides and maintains his/her specific sensor PR. As long as their PR changes only impact the xsns_xx_something.ino file I'm happy.

So sorry, no fancy testing but just plain old intuition and memory. The only testing I perform before release is with the (many) hardware lying around.

Also VSC and PlatformIO allow easy global search and change within the projext what makes changing things a breeze and that may probably be a cause for your encountered side-effects.

I guess you'll have to live with this as I seem to make additions and re-arrangements almost daily to keep the code as clean, small but extensible as possible.
