### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by vaidyasr** [arendst/Sonoff-Tasmota#4052]
I have recently installed EFM8BB1 firmware from web. Is there a way to reset back to factory defaults?. My RF bridge is not sending any more commands to trigger RF switch, but it can able to track the signals in console.

**Comment by andrethomas2** [comment]
This issue is being closed and locked because the user did not complete the template when creating the issue/request/bug report.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by andrethomas2** [comment]
According to the Wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433

The firmware you would have flashed is from:
`https://github.com/Portisch/RF-Bridge-EFM8BB1`

On this github repository you will find a file named: `EFM8_Original_Firmware.zip`

This is the original firmware which would have been on the EFM8BB1 chip.
