### ISSUE TITLE
How to change MQTT minimal interval to a lower limit (1 second)?

### ISSUE THREAD

**Issue by lev2k** [arendst/Sonoff-Tasmota#4054]
Where can I set this "minimum interval" in the Source Code?
The actual minimum of 10 seconds is too long for my project.
EDIT: And I would also like to know, where to change the resolution of the "ds18b20" from 12  to 9 or 10 Bit in the source code.

Thanks in advance

**Comment by ascillato** [comment]
Hi,

10 seconds for MQTT Teleperiod?

If you are refering to that, it is not good for your broker to have a lot of messages per second. Better should be to use instead the example in rules in the wiki to send the values of a sensor when reach a delta.

**Comment by lev2k** [comment]
This does not answer any of my questions!
So, why did you close my question?

**Comment by ascillato** [comment]
Sorry, it was answered. What you are requesting is not reliable. That is why the actual limits for the command teleperiod. 

But there is a solution without the need to modify the code, you can use the example of sending a sensor value when reach a delta as explained in the wiki in the chapter rules examples.

Your issue was closed because it was answered. General questions are better to be addressed in the discussion group or in the Tasmota Chat. Github issues are for reports of bugs and feature requests using at least the provided templates. Not a forum. Sorry.

**Comment by benzino77** [comment]
Maybe this will help you:
```
on system#boot do
   ruletimer1 1
endon
on rules#timer=1 do
   backlog status 8;ruletimer1 1
endon
```
It will send the sensor information (ie. ds18b20) every 1 second, but have not tested it ;)

> t is not good for your broker to have a lot of messages per second

it is perfectly good for most popular brokers on the market to receive hundreds of messages per second: [benchmark](http://www.scalagent.com/IMG/pdf/Benchmark_MQTT_servers-v1-1.pdf). 
What is not good is that your ESP device would not be able to send tens or hundreds messages per second.

**Comment by andrethomas** [comment]
> And I would also like to know, where to change the resolution of the "ds18b20" from 12 to 9 or 10 Bit in the source code.

Hi, the source for the driver is in xsns_05_ds18b20.ino

If you want to drop the least significant bits you can shift out the unwanted bits in the Ds18b20Read() function.

Aside from the workaround proposed by @benzino77 you can also make a mqtt call to the ESP device to give you the content of STATUS 8/10

If you send a MQTT to the Tasmota run device on its cmnd/xxx/xxx topic with the payload of "STATUS 10" it will immediately respond with a MQTT message containing the contents/output of STATUS 10.
