### ISSUE TITLE
Help needed for active switch on GPIO14

### ISSUE THREAD

**Issue by mrohner** [arendst/Sonoff-Tasmota#407]
Today my lamp is attached to a 220V socket that is switched. As I cannot just add a Sonoff in between (The Sonoff would loose power when I use the Switch), I came up with the following idea:

   regular 220V socket --------------- Sonoff- Lamp
                                         |                                               The switched 220V can the toggle 3.3V
                                         |                                               or 0V on GPIO14
switched-220V socket-Trafo - 3.3V -Sonoff-GPOI14-in

The Switch 09-12 possible on GPIO14, I understand, work when the pulled-up GPIO14 is connected to ground. What I need though is a switch that would have GPIO14 not pulled up so I can toggle the Light on the Sonoff Basic with a latched switch either 3.3V  or 0V that I would input on GPIO14.

**Comment by gajotnt** [comment]
Your question is (to me at least) a little confusing, but i have a sonoff basic connected to a two way normal wall switch, using pull up resistors and condensors to prevent signal interferance due to the long cable that goes from the wall swith to the sonoff.
And all works great, one is connected to GPIO 14 and the other to GPIO 3.

So to resume, i soldered 2 10k resistors from 3.3v to the GPIO, and on the wall switch i put a 100uF condensor. On the sonoff configured the GPIO as switches.

**Comment by mrohner** [comment]
The wall switch is 220V!

**Comment by gajotnt** [comment]
Not if you change the connection :)

**Comment by mrohner** [comment]
I do not want to dismantle my electric installation.

**Comment by gajotnt** [comment]
![example](https://cloud.githubusercontent.com/assets/25504364/25658800/3a8041ec-2ff4-11e7-8401-77b7d582554b.jpg)

**Comment by gajotnt** [comment]
Ahhh you're using diferent way. sorry did not see the photo you loaded

**Comment by mrohner** [comment]
Thanks, but this is exactly what I cannot do. My switch has to stay 220V.

**Comment by stefanbode** [comment]
Than you are in trouble :-) If your switch OFF/ON the power on the SONOFF this cannot work. The SONOFF must have 100% power on to operate (should be obvious). if you want to use 220V AC instead of the 3.3V DC to switch the lamp you need some electronics inside to translate. Typically you need a transistor, some diodes a small capacitor and a voltage split. Anyhow I'm not providing any further help because I really don't like this configuration.

**Comment by mrohner** [comment]
I decided to use a 220V relais now. It switches GPIO14 to GND. A bit an overkill but it works

**Comment by nunoronconcouto** [comment]
Hi 
Anyone can help please...?
I have sonoff with tasmota firmware....last version...i configure GPIO14 to toggle the relay ( Button 2 )..but when i connect GPIO14 with GND nothing happend...
Any ideia why??

**Comment by davidelang** [comment]
do you have a relay2 for button2 to affect?

otherwise, configure GPIO to switch1, not button2
