### ISSUE TITLE
Shelly 1 - double/tripple press and HOLD function

### ISSUE THREAD

**Issue by JDunnio** [arendst/Sonoff-Tasmota#4136]
I'm trying to figure out how the Shelly1 should be configured for the double/tripple press and HOLD function to be working.

Here is what i have configured so far:
Setoption1 1
Setoption11 1
setoption32 40 (default)
Switchmode 5

I'm working with a momentary/push-button and this is working, but I'm  not seeing the HOLD-function appearing in the console.

I've found some articles and following them, my config should work:
https://community.home-assistant.io/t/sonoff-double-triple-tap/38838

Is this functionality not working because it is seen as a switch and not a button? Or some other reason this isn't working (yet)?

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered. 

If you have further questions please do not hesitate to follow one of the provided support entry points listed below.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato** [comment]
Hi,

A switch is the key you have in your home to turn on the lights. When you touch it, it flips to on and it keeps that way until you touch again and flips to off. 

A button is a pushbutton. When you touch it, it gives you a 1 and when you release it, it gives you a zero.

So, for a switch, if you see a 1 you turn a relay on until it goes to zero. 
For a button, if you see a 1 you turn a relay on. You ignore the zero, and when you see another 1, you turn that relay off (that is called toggle) 

So, as a switch and a pushbutton are physically different, you need to differenciate them. 

Now, you can differenciate a switch from a button. 

Now, using a switch there are several configurations you can do. For getting deep into that, you need to see the commands in the wiki at switchmode. 

Besides the wiki, you can also search in issues. This was already addressed.

ESPEasy and Tasmota are different softwares aimed to different objectives with different concepts. So, if you read there, might not be the same in Tasmota and viceversa.

**Comment by JDunnio** [comment]
So concluded: the Shelly1 can't be configured as a button and only as a switch?

the physical button on the Sonoff is a (push button). If i solder a Gira push button to it, Tasmota will address it as a (push) button.
If i connect a Gira push button to the one of a GPIO-pin, it is seen as a switch. If i flip the switch and do not keep it pushed it turns off.

But when i set Switchmode1 5, the wiki says "Set switch mode to PUSHBUTTON". Now it acts like a push button should be working. But it Tasmota terms is it still a switch? like a simulated push button on a switch?

I've read a lot of topics about this, but this last part is where all topics stop and don't get answered.

**Comment by ascillato** [comment]
> the Shelly1 can't be configured as a button and only as a switch?

yes, that is in the template

> But when i set Switchmode1 5, the wiki says "Set switch mode to PUSHBUTTON". Now it acts like a push button should be working. But it Tasmota terms is it still a switch? like a simulated push button on a switch?

Yes

**Comment by JDunnio** [comment]
You are right about the template. When using the config below with a GENERIC module i got the HOLD function working as a button. I can't get a double press working with a TOGGLE message.

Generic module
GPIO4 21 relay1
GPIO5 90 Button1n

MQTT 10.0.0.13

setoption1 1
setoption11 1
setoption32 40
buttontopic ceilingfan

I've read the rules section and i think rule 16 is exactly what i need?
I've rename button1 on the example to button1n as that is what is configured?

rule on button1n#state=3 do publish cmnd/topicHOLD/power 2 endon on button1n#state=2 do publish cmnd/topicDOUBLEPRESS/power 2 endon 

After this i still get a HOLD message when i doublepress the push button.

15:03:25 CMD: rule1
15:03:25 MQT: stat/shell1/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Free":385,"Rules":"on button1n#state=3 do publish cmnd/topicHOLD/power 2 endon on button1n#state=2 do publish cmnd/topicDOUBLEPRESS/power 2 endon"}
15:03:35 MQT: cmnd/ceilingfan/POWER = HOLD
15:06:35 MQT: cmnd/ceilingfan/POWER = HOLD

Any thoughts? Would be great to get this working as it adds an extra to the stock firmware of the shelly.

**Comment by ascillato** [comment]
As answered to you in the chat:

button1n#state will not work in rules. Just use button1#state

the n in module config means NO PULL UP RESISTOR.

if you use switchtopic or buttontopic, that will override rules

**Comment by pmarq2008** [comment]
@JDunnio I am attempting to get this to work on my shelly1 and am glad I came across this. Question, to use the rule that you have set do the setoptions and buttontopic need to be set as you have in your post? Also using the rule it looks like state 3 is hold, state 2 is double and would state 1 or a single press trigger the relay on the shelly?

**Comment by brucysNZ** [comment]
Hi All.
I am trying to achieve something similar except instead of switching a Sonoff Relay, I want to turn on/off a Hue Light bulb
Is there anyway to send a service command using rules?
1. Push Push button connected to Sonoff via GPIO3
2. Toggle the push button to turn light on or off
3. The light is a Phillips hue so not connected to the Sonoff Relay
4. Only using a Sonoff to utilise the GPIO commands and or MQTT
5. I can use rule to switch another Sonoff connected to a different light. (This is NOT want I want to do)
6. Use the Sonoff to toggle a light only
Hope that makes sense?

I can use Home Assistant to control the Hue Light however I want to do it via a push button

Any help would be appreciated
Cheers

**Comment by th-s-op** [comment]
**The following is only confirmed to work with SHELLY 1 due to its hardware characteristic. Other modules might need different GPIO settings**

I was struggling with the same problem, to configure a Shelly 1 in a way that it is reacting on pushbutton presses (single, double and hold), while nothing is connected to the relay.

Like mentioned above, the solution was to change to the Generic (0) module template and set up:
- GPIO4 as "Relay 1"
- GPIO5 as "Button1in"

The GPIO5 does the magic, and it is wrong in the message above. Note the exact spelling, as specifically for the Shelly 1, it must be th "1in" button style, where "i" means inverted signal and "n" means no pullup resistor.

After this, my setup was:
# restrict to single, double, hold (you might want to leave it with the default 0!
Setoption1 1
# do not swap single and double press functionality (if you set it to 1, you have to change the states in the rule)
Setoption11 0
# single, multi-press and hold button actions 
Setoption13 0
# mode: pushbutton with hold 
SwitchMode 5
# 50 ms hold time
SetOption32 5

Now to recognize all three button press types, I use the following rule:

Rule1 
on button1#state=3 do websend [192.168.4.119] event s1=3600 endon
on button1#state=2 do websend [192.168.4.119] event s1=900 endon
on power1#state=1 do backlog power1 off; websend [192.168.4.119] event s1=1800 endon

Explanation: single press will send "event s1=900" to another tasmota device, hold for >= 50 ms duration will send "event s1=3600" to another tasmota device. Double press is special as it doesn't "send" a button state but toggles the relay. As I don't use that relay, I monitor for a toggle to ON (which is the double press), then send "event s1=1800" to another tasmota and then reset the relay to off.

You can and have to replace all the "websend ..." commands with your own functionality of course.
Then, activate that rule with

Rule1 1 

Note that if you didn't configure GPIO4 as a relay in the template, a double click will show a power toggle, but the "power1#state" rule isn't fired.

**Comment by pgorod** [comment]
In this configuration with GPIO5 as "Button1in", is there any way to test the state of the switch in a rule?

I was trying to set up multiple lengths of long press. I have SetOption32 at 40, so an event `button1#state=3` fires after 4 seconds. I'd like to set up a rule timer for a further 4 seconds, and when that one triggers, I'd like to check if the "button" is still pressed. This way I could have separate commands for 4-secs long press, and 8-secs long press.

Is it possible? Thanks.

**Comment by barbudor** [comment]
HOLD mode is a built-n function of Tasmota for Buttons. You can't create 2 different HOLD modes.
It's may be possible to do something by Configuring as a Switch with SwitchMode 1 or 2
Something like that may work for you:
```
rule1
  on Switch1#state==1 do backlog0 var1 0; var2 0; ruletimer1 4; ruletimer2 8 endon 
  on Rules#timer=1 do var1 1 endon
  on Rules#timer=2 do var1 2 endon
  on Switch1#state==0 do var2 %var1% endon
  on var2#state==1 do publish debug/hold 4 endon 
  on var2#state==2 do publish debug/hold 8 endon
```
In theory it should be even possible to extend to more hold duration

**Comment by pgorod** [comment]
Thank you for your help, @barbudor!

That works really fine - but I had to go back in the template and revert that change of GPIO5 as `Button_in`. I put it back to the default which was `Switch_n`.

This works great with your Rules in a Shelly 1 I have in my test workbench. But trying to move to a Shelly 2.5 PM which I have installed in my house it doesn't work, and I don't understand why.

The Shelly 2.5PM is modded so that the second relay is dry-contact. So SW2 will come out on O2 whenever the relay is on. The template (default) looks like this:

![image](https://user-images.githubusercontent.com/15945027/148079989-fded27ab-d5cc-456c-a8b1-863c8ed9968d.png)

So, I slightly adapted the Rules to use Switch2:

```
rule2
  on Switch2#state==1 do backlog0 var1 0; var2 0; ruletimer1 4; ruletimer2 8 endon 
  on Rules#timer=1 do var1 1 endon
  on Rules#timer=2 do var1 2 endon
  on Switch2#state==0 do var2 %var1% endon
  on var2#state==1 do publish debug/hold 4 endon 
  on var2#state==2 do publish debug/hold 8 endon
```

... but sadly the Switch state events never fire...

I think I know why this is happening, it's probably because the current coming to SW2 is 12V DC and maybe that is not enough to make the switch event trigger. Do you agree with this? And, more importantly, do you know of any workarounds?

**Comment by barbudor** [comment]
I have no idea of the original hardware of the Shelly 2.5 nor about your hardware mod.
It's may be possible to mod the hardware in a way it works, but because of my previous sentence, I can't advise here.
First, personnaly I would never mix AC voltage with low voltage on the same device.
Keep things separated and use devices that are adapted to what you want to do, or build your own device.
I know that Shelly have the advantage of being very small but for the same reason, I wouldn't tinker too much with them.

**Comment by pgorod** [comment]
Ok. The mod is working fine, I guess, but I realize all this needs to be done carefully and I appreciate all the advice I get here, pointing me in that direction.

But taking my question to the essentials only, do you know if I should have any hopes of ever getting a 12VDC signal connected to GPIO5 as Switch to provide me with a Switch event? Or is it beyond the physical characteristics of the processor?

**Comment by barbudor** [comment]
The processor itself is only compliant to 0...3V3
Any voltage above 3V3 directly aplied to the processor will generate the "magic smoke" telling you the device is good for the trash
What Shelly is including is some hardware to adapt the external signal to what the processor can accept. As some option is connecting to the AC voltage, it is likely some optocoupler are there to isolate the processor from higher voltage.

So it should be possible to connect a 12VDC signal to trigger the GPIO.
If you were using a NodemMCU or any similar board, I would advise you with a safe schematic.
However, I don't know Shelly's schematic. Making a wrong move could be at risk for the processor but as there is AC mains floating around there is also a high security risk.

**Comment by Noschvie** [comment]
@pgorod : have a look to "Optocoupler Isolator PLC Signal Level Voltage Converter Module 12 V to 3.3 V"

**Comment by pgorod** [comment]
Thanks for your explanations, I get it now. I'm not very handy with electronics (the mod on the Shelly was done with the help of a friend) so I am not going down this path. Instead I will try making my button operate the full 220V, and this controls the Shelly's decisions with the Rules suggested above. Then I will figure out some other way to trigger the 12V dry contact, maybe an extra relay, maybe an extra Shelly 1, I'll have to see if I can fit it in the tight space I have. Thanks everybody, this thread was very educational for me!
