### ISSUE TITLE
how to make it work as a button ?

### ISSUE THREAD

**Issue by mahdy89** [arendst/Sonoff-Tasmota#4215]
please help me what i should put in the rules??

i want it to turn  on for a second then off
so  its like a push button (of on release)

**Comment by ascillato** [comment]
Hi,

Sorry that you skip the troubleshooting template. A lot of information is missing in order to properly help you. 

I don't understand what you want. I guess that you want to push the pushbutton in a sonoff basic and when it is pushed, the relay 1 is on, and when you release the pushbutton it turn the relay off. 

If that is the case you need to use module generic and set the gpios as your device but instead of using Button1 use swicth1

Then go to the console and type switchmode1 1 in order to make it follow what your button does. 

If that does not solve your issue, please complete the troubleshooting template and give a detailed explanation of what you want.

If you don't want to use the troubleshooting template, please ask your question at the Tasmota Chat. Thanks
