### ISSUE TITLE
configuration of time zone geo location and static IP address via web interface possible?

### ISSUE THREAD

**Issue by Jens1973** [arendst/Sonoff-Tasmota#4257]
Hello Theo,
Hello Tasmota community,

thank you for developing tasmota. It is a great firmware for Sonoff devices without the need of vendors's cloud. It is nice that I can configure the device now (I use Tasmota firmware on a wi-fi power socket from german DIY store OBI). It would be nice if I could configure time zone and geo location for the timer and it also would be nice if I could configure IP address manually. Is it possible to add these configugation features to the web interface of tasmota firmware?

best regards

Jens

**Comment by andrethomas** [comment]
@Jens1973 

Since your interest in this great firmware is so high, have you considered reading the Wiki?

Especially since the part which would have answered all your questions is posted here https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

Look for Timezone, TimeDST, TimeSTD and IPAddress1,IPAddress2 and IPAddress3

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
