### ISSUE TITLE
Sonoff SC Sensors do not work v6.3.0

### ISSUE THREAD

**Issue by fit47919** [arendst/Sonoff-Tasmota#4301]
After updating my Sonoff SC to 6.3.0 the sensors won't work anymore. What can cause that problem?
Thank you
![2018-11-07 00_45_35-sonoff - main menu](https://user-images.githubusercontent.com/33380915/48101295-bfd76880-e226-11e8-95cf-042a74ea0f3a.png)

**Comment by wongnam** [comment]
On Sonoff SC if you replace a stock DHT11 sensor to DHT22(AM2302) it's ok, but it's not working if you replace stock sensor to a non-iTead SI7021 because non-iTead SI7021 is dual-wires sensor.
please notice that:
- iTead Sonoff SI7021 is single wire sensor.
- other SI7021 is dual wire sensor.

FYR: https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
