### ISSUE TITLE
unstable (just if MQTT 

### ISSUE THREAD

**Issue by stephan2k** [arendst/Sonoff-Tasmota#4394]
Hello,

I have a few sonos devices (Basic, s20, pow) and with all the same problem:
If MQTT is activated (connected to iobroker) the device is not running stable.

For example:
If i powered on 5 devices via iobroker…. one day later Maybe just one device is running.. Ther other devices are powerd off....
I installed to newest Software yesterday via ota 

`

Program Version | 5.14.0
-- | --
2018-05-15T15:29:54
2_3_0/1.5.3(aec24ac9)
1T21:54:41
254 at F7000
41
Software/System restart
DG TV
 
WiFi name(78%)
SH-sonoff-s20-1
10.xxx.xxx.xxx
10.xxx.xxx.xxx
255.255.255.255
10.xxx.xxx.xxx
5C:CF:7F:7D:42:ED
 
10.xxx.xxx.xxx
1883
DG_Fritzbox_TV
Stephan
sonoff
sonoffs
cmnd/sonoff/
 
None
Enabled
Web Server
 
8209133
1327198
1024kB
1024kB
526kB
476kB
17kB

`

If MQTT is disabled and i powered on a device via web page… it runs days without Problems.

i am really dissapointed, can anybody help me?

Thanks in advance

**Comment by ascillato** [comment]
You are running a very old version. Please update

**Comment by ascillato2** [comment]
Please, next time use the troubleshooting template in order to give us information to properly help you.

Please update to last Tasmota version from the development branch at http://thehackbox.org/tasmota/sonoff.bin

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by stephan2k** [comment]
Sorry i updated the devices, but the same issues...


Program Version | 6.3.0.10(5ee6922-sonoff)

In the iobroker log i can see:
sonoff.0	2018-11-22 15:37:28.832	warn	Old client DG_Fritzbox_TV with secret 1542897310155_3591 sends pingreq. Ignore! Actual secret is 1542897447944_3281

-> and then the button / power is powered off....
whats wrong?

**Comment by ascillato** [comment]
Your log: `warn	Old client DG_Fritzbox_TV` is not related to Tasmota. Sorry.

> and then the button / power is powered off....

Sorry, I don't undertand what you meant. You press the button and then goes the power to OFF ? which button?

**Comment by stephan2k** [comment]
Sorry :)
example:

I switched on a sonoff device (no different if i switched on it via web interface or iobroker).... it´s not running constant... for example till i switch off the device...

After a not specific time, the device is switched off automatecally and i can see the message in the log from the iobroker...
if i disable MQTT (connection to iobroker) its running without problems

Hopefullly i explained right

**Comment by ascillato** [comment]
Ok, now, please, for helping you, we need more information. Without information we are blind and just guessing what can be your problem.

This is the third time I'm asking you to please please complete the **_troubleshooting template_**:

------------

**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [ ] Hardware used : 
- [ ] If a pre-compiled release or development binary was used, which one? :
- [ ] You have tried latest release or development binaries? :
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

-------------------

And also, besides that, go to the console and type `weblog 4` in order to have more debug information to "see" where is coming from your power OFF command. Please, share also the output of the console when this power OFF happens.
