### ISSUE TITLE
GPIO 0 Relay does not work

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#440]
Really strange, but I also tested the sonoff.ino.bin you attached to 5.0.6. As long as I bind a relay to GPIO 1+ it is working. Only the GPIO0 does not work. Because this is on the Wemos the quite common pin D3 i was wondering why on hell my relay did not work again. maybe you can have a look and comment on it. thx.

**Comment by arendst** [comment]
See #377

**Comment by stefanbode** [comment]
Hi Arend, I agree on the switch issue, but is it the same for the Relay? The strange this is, I'm pretty sure it was working before. will upload an earlier version to verify.

**Comment by stefanbode** [comment]
I just did additional test with wemos mini and nodemcu and some older devices with 5.0.3 firmware. It looks for me that relay on GIO 0 was working in 5.0.3 and is broken in 5.0.4. Neither the nodemcu nor the wemos will work with the "actual" firmware on GIO 0

**Comment by arendst** [comment]
Did a test with firmware 5.0.7 using a Wemos D1 mini (clone) and configured a relay on GPIO00:

![image](https://cloud.githubusercontent.com/assets/11044339/25988933/57222ba0-36fa-11e7-91ff-41091202c8dc.png)

Connected the relay like:

![image](https://cloud.githubusercontent.com/assets/11044339/25988779/a60d4b38-36f9-11e7-9cf5-be6a5ed405ab.png)

And all works as expected although the relay toggles after power on with ``PowerOnState 0`` due to the external pull up resistor R10 on my version of the Wemos D1 mini:

![image](https://cloud.githubusercontent.com/assets/11044339/25988987/9d1e578c-36fa-11e7-976a-ad3f6ca91db6.png)

What's the exact schematic(s) you are using compared to your real hardware?

**Comment by stefanbode** [comment]
My mistake.... sorry to bother...
