### ISSUE TITLE
Couldn't plain inputs be counted as devices_present?

### ISSUE THREAD

**Issue by onkelbeh** [arendst/Sonoff-Tasmota#4422]
Afaik you have to configure an output, even if it's only a dummy for every input line to be counted. This limits your input lines for example on a NodeMCU with an ESP12 to **half** the physical GPIO’s you have. Why can’t plain inputs be counted as devices, at least for the generic module?

As a workaround, i manually set devices_present after the count routines in `GpioInit()`, as an example on 6.3.0.12 i simply set `devices_present = 8;` in line 2541. This allows me to used nearly twice the amount of lines on an ESP8622-12, so i could connect 8 wall switches to a single Amica NodeMCU.

![img_2832w](https://user-images.githubusercontent.com/42828703/48965985-8cd3f980-efc8-11e8-8efd-33962903653d.jpg)

<img width="405" alt="bildschirmfoto 2018-11-24 um 08 13 55" src="https://user-images.githubusercontent.com/42828703/48965976-775ecf80-efc8-11e8-8f40-8db34437624b.png">

<img width="369" alt="bildschirmfoto 2018-11-24 um 08 13 30" src="https://user-images.githubusercontent.com/42828703/48965973-6ada7700-efc8-11e8-8dcc-d4d997291b04.png">

Some could say to use ESPEasy for your inputs, but many sensor implementations i use are managed way better and more reliable on tasmota (e.g IRremote, mqtt, mqtt/telemetry, DS18B20, MagicHome).

My wish would be either a change in the count routine, to count a Switch or a button like a relay, or a SetOption to override devices_present without the need to recompile.

**Comment by ascillato** [comment]
Hi, you don't need to add dummy relays. You can add just the inputs you need.

Please check the examples at rules in the wiki

**Comment by ascillato** [comment]
I use a setup very similar to the one you have posted and works fine without need to modify anything.

The only thing is that you have to define rules for the input switches in order to tell Tasmota what you want to do. 

Settings up as you posted, is taken by Tasmota as a ladder switch by default. So all the switches will control that one relay only. 

So, using Tasmota beyond that default, you need to use rules to tell Tasmota what fo you want to do. 

You can make any behaviour you want for any of the switches like sending mqtt messages, powering relay of other switches, turning timers, etc etc.

**Comment by ascillato2** [comment]
If you need more help, please just ask here or in the Tasmota Chat. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
