### ISSUE TITLE
OpenHAB documentation obsolete

### ISSUE THREAD

**Issue by sgofferj** [arendst/Sonoff-Tasmota#4675]
The MQTTv1 binding in OpenHAB has been deprecated and disabled recently. Therefore, the documentation under https://github.com/arendst/Sonoff-Tasmota/wiki/openHAB is obsolete.
Updating the documentation might be good because the item examples don't work any more.

**Comment by ascillato** [comment]
Please update it. Wiki is open for community to edit.

**Comment by meingraham** [comment]
@sgofferj,

Hold 'dem horses!

The openHAB2 version of the MQTT binding has just been release and is still somewhat in its infancy. As such, there are a few hiccups still showing up and also a few features not yet fully fleshed out.

The MQTT v1 binding is still available. It has just been moved to "legacy" status. It can coexist (i.e., be installed) with the v2 binding. There are still many users (i.e., 99.99999%) still on the original binding. In fact, there are some use cases that currently can only still be accomplished with the v1 binding. In some cases there are workarounds which require additional scripting in openHAB. In some cases, there is no equivalent capability. Thus, getting rid of the TASMOTA openHAB wiki is premature!

At most, one might argue for a note in the wiki to make users of TASMOTA with openHAB aware of the new openHAB2 binding. Then, one might make the case to retain the v1 as a "if you are still using MQTT v1...". Finally, the wiki ought to have an equivalent section to what is currently present in the wiki **ADDED** to the page but adjusted to reflect the necessary syntax when using MQTT v2.

Respectfully,

Mike

**Comment by sgofferj** [comment]
@meingraham 
Thanks for the clarification. I spent about an hour literally sitting in a cold and dark apartment after an automatic update moved my installation to v2 and disabled v1 :D.
A quick forum search found David Graeff saying

> It will “replace” (as in: make it obsolete) the mqttv1 binding within the next couple days, which stops all support for the old binding.

[here](https://community.openhab.org/t/reliability-of-binding-mqtt/59646/6), which triggered a little panic mode :D.
I got it back working with some reading and some help from the openhab forum. Just wanted to spare other users the same experience, hence I opened that issue here.

@ascillato2 
I do appreciate developers being busy but not everybody reporting an issue has the time or the skill to do something about it. In this case, I for example don't know anything about the MQTTv2 binding except that it's coming.

**Comment by meingraham** [comment]
@ascillato - I realize that this is not the openHAB forum... but if anyone runs across this issue, I wanted to ensure completeness to my earlier post.

The openHAB MQTTv1 and MQTTv2 fortunately have different component IDs. Therefore they can both be installed concurrently. This will allow users to update openHAB and migrate to the v2 binding over a period of time (i.e., not overnight!).

Since the openHAB2 MQTT binding is now officially released, the v1 binding has been marked as legacy. This means it will not be updated. However, it still runs perfectly under openHAB 2, at least as of 2.4. In order to install it, edit the addons.cfg in the services folder and make sure there is a line that reads "legacy = true" and that it is not commented (i.e., prepended by #). This allows legacy bindings to be installed from the openHAB "legacy" repository online.

It's probably a good idea to start migrating now while both bindings are viable concurrently. It's likely that the v1 binding will cease working sometime in the (hopefully distant) future.

Mike

**Comment by ascillato** [comment]
@meingraham Totally agree with you.

**Comment by meingraham** [comment]
Added note to wiki page
