### ISSUE TITLE
Sonoff T1 MQTT Status LED disable

### ISSUE THREAD

**Issue by Trulli2012** [arendst/Sonoff-Tasmota#4733]
If MQTT is on and the server is not reachable the LED is blinking. Is it possible to deaktivate it? Ledpower 0 ans ledstate 0 doesnt work

**Comment by Jason2866** [comment]
Use case? If you dont need mqtt switch it off.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by Trulli2012** [comment]
setoption31 0 does not work. And yes Mqtt is intentionally activated. But the server is running unstable and if the server crashes the LED on Sonoff T1 flashes and in the bedroom it is annoying. Actually I also assume that if I set ledpower to 0 no LED will blink or light up anymore. Good the LEDs under the button are connected to the relay but at least the Wlan led should stay off.

**Comment by ascillato2** [comment]
Hi, sorry.

The command is `setoption31 1` to turn off the led blinking when there is no mqtt or no wifi.

Please, check the wiki at commands for more information (https://github.com/arendst/Sonoff-Tasmota/wiki/Commands)

Please, next time use the troubleshooting template. That gives us more information to properly help you and also gives you some previous steps for you to check like search in issues. This issue is duplicate and has been addressed before. Thanks
