### ISSUE TITLE
Tasmota 6.4.1 DNS Resolve not work

### ISSUE THREAD

**Issue by m0rph2k** [arendst/Sonoff-Tasmota#4781]
Hi

After tasmota update from 6.3.0 to 6.4.1 my Sonoff TH16 can not resolve my MQTT Server FQDN. IP Adresse works fine. Downgrade to 6.3.0 and the name resolve works

Anyone have the same problems ??

**Comment by m0rph2k** [comment]
With a older version 6.2.1 the name resolve works. With 6.4.0 not

**Comment by andrethomas** [comment]
@m0rph2k Do you mean mDNS?

**Comment by andrethomas** [comment]
The .local TLD is reserved for mDNS so unless you're explicitly using mDNS it will fail. It worked on core 2.3.0 because core 2.3.0 wrongfully allows failover to conventional DNS when mDNS broadcast requests failed.

Please see issue https://github.com/arendst/Sonoff-Tasmota/issues/4670 for more information as this was previously discussed.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
