### ISSUE TITLE
6.4.0/6.4.1 Wifi issue

### ISSUE THREAD

**Issue by vampywiz17** [arendst/Sonoff-Tasmota#4795]
Hello there,

In this version, Sonoff basic constantly reconnect wifi (known issue: https://github.com/arendst/Sonoff-Tasmota/issues/4697). The 6.3.0 and a own-compiled version (6.4.1) with Core/SDK  2_3_0  working well.

My question, that the future you will plan to fix this, or we need to use the alternate version (with 2.3.0 SDK)

**Comment by Jason2866** [comment]
You can use core 2.3.0 so long Tasmota is compiling without errors.
Since 2.3.0 is rather old and outdated newer upcoming features from Tasmota will maybe incompatible
or simply not possible.
For core 2.4.2 there will be no fixes anymore from the Arduino core team. 
It works for most users and the sleep bug is solved because Tasmota uses his own sleep routine since 6.4.xx For 2.4.2 the Alexa bug (Arduino core bug!) is fixed in precompiled firmware.
Tasmota is heading to version 2.5.0. (beta2 is quiet stable)
Alexa bug is fixed in core and working without a patch. For the users who has wifi issues with 2.4.2. 
2.5.0 is most of the time a solution.
Core 2.4.2. and 2.5.0 does solve software serial problems that 2.3.0 has 
But most important feature it frees RAM!
see infos in [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk)

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
