### ISSUE TITLE
Added configuration for TYWE3S module on YTF Universal IR device (send & recv)

### ISSUE THREAD

**Issue by pastudan** [arendst/Sonoff-Tasmota#4855]
I was looking for a smart IR device to control some IR curtains, and tried this YTF Wifi Smart IR remote from Amazon (https://www.amazon.com/gp/product/B07H46LJZK). 

Unfortunately the app didn't allow custom programmed IR codes to be hooked up to Automation / Google Home / IFTTT (only predefined ones), so I cracked it open to see what was inside and if it was hackable. I became hopeful after seeing what looked like a familiar ESP8266, and discovering that the TYWE3S is exactly that. 

I stumbled across this repo in my googling, and decided to give it a try. Got it running with no problem, and I wanted to share my pin configuration after a few hours of trial and error:

```
{ "YTF-Universal",
    0,                  // GPIO0
    0,                  // GPIO1
    0,                  // GPIO2
    0,                  // GPIO3
    GPIO_LED1_INV,      // GPIO4 Blue Led
    GPIO_IRRECV,        // GPIO5 IR Receiver
    0,                  // GPIO6
    0,                  // GPIO7
    0,                  // GPIO8
    0,                  // GPIO9
    0,                  // GPIO10
    0,                  // GPIO11
    0,                  // GPIO12
    GPIO_KEY1,          // GPIO13 Button
    GPIO_IRSEND,        // GPIO14 IR Transmitter
    0,                  // GPIO15
    0,
    0                   // ADC0 A0 Analog input
  },
```

![img_2323](https://user-images.githubusercontent.com/1296162/50830734-8b069100-12fd-11e9-9c4d-130d17056257.JPG)
![img_8334](https://user-images.githubusercontent.com/1296162/50830737-8b069100-12fd-11e9-83b0-1d9b1ee42fb9.JPG)
![img_3255](https://user-images.githubusercontent.com/1296162/50830739-8b9f2780-12fd-11e9-83b3-bdaea3f50bb2.JPG)
![img_3282](https://user-images.githubusercontent.com/1296162/50830740-8b9f2780-12fd-11e9-9a11-9572d9990e44.JPG)
![img_1140](https://user-images.githubusercontent.com/1296162/50830738-8b069100-12fd-11e9-968a-ed93e396c614.JPG)

This device is a sleek little smart IR module for ~$30, and this software makes it a ton more useful. Thanks!

**Comment by Jason2866** [comment]
Great finding, could you add to wiki please?
Thx!

**Comment by ceaswaran** [comment]
@pastudan Great work. i happen to buy a Tuya app based universal IT remote, I have flashed it with TASMOTA.
Product Link: https://www.aliexpress.com/item/Zemismart-IR-Bridge-Control-Air-condition-Fan-TV-For-Smart-Life-App-Google-Home-Alexa-Echo/32922000072.html?spm=a2g0s.9042311.0.0.35214c4dTdP77D&fbclid=IwAR2vFVs9KPsP4d6DKNMCrmDJtk8iwrhP1RHjEB4U6odEAzy-W_0_ovPj7-0

I was able to figure out IR receive & Send GPIO (ref below image)

![02](https://user-images.githubusercontent.com/40624146/50841067-e54d3380-1389-11e9-8bfe-866136048bf6.jpg)
![03](https://user-images.githubusercontent.com/40624146/50841068-e67e6080-1389-11e9-9709-9232653cd987.jpg)
![04](https://user-images.githubusercontent.com/40624146/50841069-e67e6080-1389-11e9-94f5-a4f5a2f9ab62.jpg)
![05](https://user-images.githubusercontent.com/40624146/50841070-e67e6080-1389-11e9-8dd8-78e6e9b05405.JPG)

**Query:** 
1. My TV Remote has a single POWER button . Which Pressed 1st time TURN ON. 2nd Time TURN OFF. In tasmota console using IR receive I see the same code when I pressed the power button once or twice. If I send the same code (Which I received using IRreceive) I see TV only TUN ON. TURN OFF NOT WORKING. please help

OFF: IRsend {"Protocol":"NEC","Bits":32,"Data":50153655} WORKING

ON: IRsend {"Protocol":"NEC","Bits":32,"Data":50153655} NOT WORKING

2.  None of my AC (Air conditioner's) Remote is unable to recive or send the IR signal.Since all my AC's protocal is UNKNOWN i am try to receive RAW codes. but AC RAW dosent work in Tasmota
teminates half way as below dot dot dot
`19:07:25 MQT: tele/sonoffir/RESULT = {"IrReceived":{"Protocol":"UNKNOWN","Bits":114,"Data":2896510163,"RawData":[3788,1448,622,1136,616,1138,592,442,590,442,614,418,590,1160,618,418,612,418,622,1134,592,1054,726,416,614,1090,664,452,580,414,616,1138,616,1136,620,416,616,1136,618,1136,618,416,616,454,580,1134,618,414,618,414,620,1136,616,454,580,414,616,416,618,414,618,414,618,414,616,414,620,452,580,416,614,416,616,418,614,416,616,452,580,452,578,418,620,416,616,414,616,416,616,416,616,418,616,1134,618,416,616,418,618, ...`

@arendst advised to change the tasmoto source with following values
`my_user_config.h
IR_RCV_BUFFER_SIZE 1000
IR_RCV_TIMEOUT 50
PubSubClient.h and sonoff_post.h
MQTT_MAX_PACKET_SIZE 2000` 

, but still with those changes i dont get the full RAW code.

Have you come across these issues? Do u have a solution?

**Comment by andrethomas2** [comment]
Closing this issue as it the PR made for this request has been merged into development.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ceaswaran** [comment]
@pastudan prefixed 0 & added code till dot dot dot. using IRsend
none of the AC's work :(

**Comment by jandae** [comment]
I got the same device, how do I apply your configuration? Sorry very new to this

**Comment by viertaxa** [comment]
This seems to be the same layout for the Monoprice Stitch device. (Same hardware)

**Comment by viertaxa** [comment]
Interestingly, I had to cut the trace going from the RX and TX serial pads towards the USB port. It appears they were being bridged somehow, causing all sorts of serial errors.

**Comment by arendst** [comment]
@viertaxa nice solution. In the latest development versions I disabled serial comms for this device which also solves the serial loopback issue. So no need to cut wires.

**Comment by pastudan** [comment]
@viertaxa thanks for mentioning that. I thought I just had a faulty device! I didn't have the loopback issue when I first loaded the firmware, but it popped up later. Can you show an image with exactly which trace you cut? My PCB is black so it's difficult to follow the traces.

I wonder why they would bridge those 🤔

**Comment by Jason2866** [comment]
@pastudan  load latest firmware and you dont have this issue without cutting traces

**Comment by pastudan** [comment]
@Jason2866 @arendst wouldn't that create a problem where you can't configure your device over serial? I needed the serial interface to configure my wifi username / password after loading the sonoff firmware, since I didn't want to take the time to compile a version with them built in. Maybe there's a better way I'm missing?

**Comment by Jason2866** [comment]
Via wifi. Read wiki...

**Comment by jamietang68** [comment]
@pastudan 
Do you mind to share how did you set the device into flashing mode? I have the exact same unit, but couldnt set it into flashing mode.

I tried shorting GPIO 0 to GND and RST to GND, but failed.

Thanks!

**Comment by pastudan** [comment]
@jamietang68 if I recall correctly, you need to connect GPIO 0 to GND during boot, and then release it during flashing

**Comment by jamietang68** [comment]
@pastudan Thanks for reply. Yeah i tried that but it doesnt seems to work.. do you remember if the blue led is blinking or stays on during flashing mode?

**Comment by meingraham** [comment]
If any LEDs blink while powering up then it didn't go into programming mode. When GPIO0 is grounded (and kept grounded for 3-4 seconds), no LEDs should light.

**Comment by jamietang68** [comment]
@meingraham got it! thanks for the info!

**Comment by rjcooper725** [comment]
Anyone still here?  I develop tech for special needs kids.  I am wanting to control this YTF IR blaster via a iOS app.  Is there an API or has anyone hacked with Python or something?
RJ :)

**Comment by pastudan** [comment]
@rjcooper725 this firmware supports MQTT which is a well documented API that you could build an iOS app around. https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview

**Comment by ascillato** [comment]
@rjcooper725, besides MQTT, Tasmota also supports control over HTTP and over KNX IP MULTICAST

See wiki at: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands for control over HTTP

**Comment by rjcooper725** [comment]
Hi!

Please check this one out for me? (IR blaster)

Tx!

**Comment by 2016for** [comment]
Thanks for providing the pinout for this device @pastudan.

Slightly off topic, but I want to use the codes from [IRRemoteESP8266](https://github.com/markszabo/IRremoteESP8266) (as that's the only library that has my Fujitsu AC codes), can I create my own firmware using that library and flash it onto this device using these pins?

Thanks again for the information!

**Comment by ceaswaran** [comment]
@2016for  use Tasmota it can send receive raw codes

**Comment by 2016for** [comment]
Hey I am finally ready to flash this. Any suggestions on how to flash it without having to solder wires onto the flat PCB solder pads?
(Want to backup firmware before flashing, so I don't think Tuya-Convert will be helpful)

**Comment by arduino43** [comment]
Tuya Convert does backup firmware

**Comment by damocles-git** [comment]
Hello, I flashed this IR blaster:

> @pastudan Great work. i happen to buy a Tuya app based universal IT remote, I have flashed it with TASMOTA.
> Product Link: https://www.aliexpress.com/item/Zemismart-IR-Bridge-Control-Air-condition-Fan-TV-For-Smart-Life-App-Google-Home-Alexa-Echo/32922000072.html?spm=a2g0s.9042311.0.0.35214c4dTdP77D&fbclid=IwAR2vFVs9KPsP4d6DKNMCrmDJtk8iwrhP1RHjEB4U6odEAzy-W_0_ovPj7-0

and it works only when I power the esp directly from the usb/serial programmer, but if I power it from the microusb connector it does not show any working activity, green leds are powered and the voltage in the gnd and vcc pins are correct.

I am out of ideas :-( ... any idea why it might be happening?

**Comment by arduino43** [comment]
Can you upload a picture of the internal board/PCB?

**Comment by ceaswaran** [comment]
@damocles-git i use it with tasmota . are u able to see sonoff-XXXX wifi?

**Comment by damocles-git** [comment]
> Can you upload a picture of the internal board/PCB?

I'm sorry, I forgot to upload them:

![ir-blaster-1](https://user-images.githubusercontent.com/16701920/58408553-560d9780-806e-11e9-971a-1bdcaefb61bf.jpg)
![ir-blaster-2](https://user-images.githubusercontent.com/16701920/58408558-586ff180-806e-11e9-8131-36e11460d52c.jpg)

**Comment by damocles-git** [comment]
> @damocles-git i use it with tasmota . are u able to see sonoff-XXXX wifi?

Hi ceaswaran, yes .. I can use tasmota with the esp8266 chip (this is mqtt and http) only when it is powered directly from the serial programmer even the green leds are on, wifi settings are configured through the user_config_override_sample.h file, but when I disconnect the programmer and use the microusb connector to power it the green leds are on again and not wifi activity is showed in my wifi network, no smartconfig, nothing!

**Comment by arduino43** [comment]
Did you flash the chip using DIO? This happened to me when using DOUT before.

**Comment by damocles-git** [comment]
> Did you flash the chip using DIO? This happened to me when using DOUT before.

I flashed it with DOUT, as stated in the wiki:

`Only Flash Mode DOUT is supported. Do not use Flash Mode DIO / QIO / QOUT as it might seem to brick your device.`  

this is my command line: 

'esptool.py -c esp8266  -p /dev/ttyUSB0 -b 921600 write_flash --flash_mode dout --flash_size 1MB 0x0 sonoff-6.5.0.2.bin'

**Comment by damocles-git** [comment]
Finally it worked :-)

Normally I use an usb hub to connect the devices, I test it with a different power adapter and it worked, very big thanks for this fantastic software!!

**Comment by Plexcon** [comment]
> @pastudan prefixed 0 & added code till dot dot dot. using IRsend
> none of the AC's work :(

Were you able to fix the dot dot dot issue?

**Comment by thomas-lentz** [comment]
Hi Pastudan,
how did you open the IR Blaster? There aren't any screws visible on mine.

Thanks for your help.
Greetings
 Tom

**Comment by arduino43** [comment]
If I remember correctly you have to use a thin screwdriver or knife to get the case open (separating the top and bottom of the case).

There is a way to do it without snapping plastic or otherwise damaging the unit, just move around the edges until you feel a spot with less resistance and start applying a little pressure there.

**Comment by arduino43** [comment]
I just looked at my device and it seems like the place to start is the green highlighted area in the attached photo

https://imgur.com/a/XtxcgVC

**Comment by thomas-lentz** [comment]
Hi Arduino43,
thank you for your quick help - that worked fine.
Greetings
 Tom

**Comment by Freakadude** [comment]
Hi,
I have 3 tuya type Plugs which i successfully flashed with the tuyaconvert OTA method. I also have this same YTF tuya type IR bridge and wanted to flash it as well via the same method since based on the wiki it should work the same without having to crack the unit open.

I did the exact same steps as i did with the plugs. I put the YTF bridge into pairing mode (blue led blinking fast) and then started the flashing process. Initial results show that the convert program is connecting to the device as the flashing stops after a few seconds and i get a solud blue led which then turns off. 

Unfortunately the flashing process does not go further from this point onwards. The original FW is not downloaded and i cannot flash tasmota.

Is there something i should do differently for this to work? Don't really want to crack the unit open and solder. I just want to get the same tuyaconvert OTA method working if thats a doable way.

Cheers

**Comment by ffleandro** [comment]
@Freakadude Did you manage to flash tasmota using tuya convert?
Also interested in this.
Thanks

**Comment by koivunen** [comment]
A listing in Aliexpress promising TYWE3S (with pictures) shipped me a WR3E so be careful with new devices. 
The seller shipped me the correct version afterwards but did hint me that Tuya has stopped selling TYWE3S chips.

**Comment by ffleandro** [comment]
I managed to flash an YTF IR Bridge (TYWE3S) using tuya-convert without needing to open it's case or solder any wires.

**Comment by ffleandro** [comment]
@koivunen Regarding these new non-ESP based devices, here is a full thread discussing them: 
 - https://community.home-assistant.io/t/unkown-tuya-chip/153591/85

**Comment by s-hadinger** [comment]
Please refrain from posting in an old and closed issue. Reach out on Discord.

The encoding is explained here: https://tasmota.github.io/docs/IRSend-RAW-Encoding/ and there's an online tool to convert to uncompressed format

**Comment by adrianslabu** [comment]
> How to handle some raw data like what I'm getting from my ceiling fan,
> {"IrReceived":{"Protocol":"UNKNOWN","Bits":312,"Hash":"0xDA16662A","Repeat":0,"RawData":"+615-635+595bC-1635+565d+590-1610E-1660+540-1690+535-670FgF-1640E-695+570-690I-4745C-685F-665A-1580F-1605+620-1590+560gVgF-720KgE-1615FpOpF-4720V-715I-715I-1630E-1585FmCgEg+430-940+510mE-1585+645-725+485-740I-4840+610-710IrCuVtFwA-1585N-1560EnF-1560VzXyEnE-4750FpKpEhEgEdFhI-1665IlFt+645-1585F-775+485pE-4805XsKpO-1630F-1585VgFgFgVaV-1680+495gAsVl+640-4775VbVrI-1630Ou+625t+600-1600V-1585VnIhEmCp+510-715E-4720V-660FpA-1530V-1585AdF-1585V-1585E-700FdEgC-640CpFqO-715FbV-1550CdCgA-1560FmCsFtVmE-640VsC-4880Fa+640-745+510tVgF-1585VgFwA-700XtVgFnEsF-4725VrIsV-1630EtAgF-1585VgFlFmX-1585A-750+485pC-4775EpErFtCgFgOmF-1585Vy+510dFzEpFyI-4855V-640A-660CuEgFgVmEt+645-640CuFgE-750I-640+640-4700AsFpOh+520-1630FgE-1665EdInE-1720+510zA-645FlE-4770C-630C-750+505-1630EdFtVdI-1670IsVgFmEsEsA-4860Ln+480yK-1630FgEdFzFtVnXmFzX-640V-770+485-4800+515yXlXh+510-1665XgF-1665F-1560+640-640CmIdKnVpX-4775OpEsFgXdAwFgEmCy+51

Go to [https://tasmota.hadinger.fr/util](https://tasmota.hadinger.fr/util) and paste the code from your RawData and press Go to decode it.
Send the resulted code from output using IRSend like below:

`IRSend 0,your_decoded_raw_data`

Exemple:
If your decoded rawdata is `1200,475,1220,455,390,1290,405,1280,390,1290,390,1290` you have to use `IRSend 0,1200,475,1220,455,390,1290,405,1280,390,1290,390,1290`

**Comment by floydcohen** [comment]
> I managed to flash an YTF IR Bridge (TYWE3S) using tuya-convert without needing to open it's case or solder any wires.

Can you give some info about how to do this?

**Comment by adrianslabu** [comment]
> > I managed to flash an YTF IR Bridge (TYWE3S) using tuya-convert without needing to open it's case or solder any wires.
> 
> Can you give some info about how to do this?

Find here all the information you need:
https://github.com/ct-Open-Source/tuya-convert
