### ISSUE TITLE
China only sonoff module for Canada

### ISSUE THREAD

**Issue by BrianZZh** [arendst/Sonoff-Tasmota#5000]
I recently obtained multiple Chinese sonoff modules and on the box it says that it only works within mainland China. However, I was wondering if I can flash the module and have it work in Canada. Do you guys have any suggestions? Thanks a lot!
The following are the photos of the module.

![img_2608 jpg](https://user-images.githubusercontent.com/46920230/51522827-19d7db00-1ddf-11e9-9495-e2d4daa30253.JPG)
![img_2609 jpg](https://user-images.githubusercontent.com/46920230/51522833-1cd2cb80-1ddf-11e9-9c26-269197baa5a4.JPG)

**Comment by mike2nl** [comment]
@BrianZZh 
- 1st congrats for nr. 5000
- 2nd it is a Sonoff Basic R2 v1.1
- 3rd look at the wiki and there you find your answer. 
Search there in the list on the right side of that wiki page, please. 
All hardware which is supported is listed there.

More answers could not be given because it is no issue.
For these and other question first look at the wiki and read, and read again.
Then we have the discord server to ask questions. This is told you by opening this issue.

So pleasse, follow the rules so as everyone ;-).

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by AlexTransit** [comment]
I have such modules.
The firmware works, but there may be some minor problems.
if MQTT is enabled and there are many messages, the module restarts.
look ESP ID
`esptool.py chip_id`

check is simple.
turn on PWM and MQTT
and quickly switch the slider several times.
if the module does not reboot, then everything will work fine.
