### ISSUE TITLE
Sonoff Basic with MCP23017 and HC-SR501

### ISSUE THREAD

**Issue by speedyrazor** [arendst/Sonoff-Tasmota#5036]
I have a Sonoff Basic, I02 for light switch, a MCP23017 I2C Serial Interface to expand the GPIO’s, on the I2C bus I have:

GY-BME280 Temperature Humidity Sensor
GY-302 BH1750 Light Intensity Illumination Sensor

These two sensors are working in the Basics GUI, but I am trying to also use a PIR motion sensor:

HC-SR501 Human Sensor

Which i have connected to A0 on the MCP23017. I am trying various sensor29 configurations, but am a bit unsure of how to get an MQT message working whenever motion is detected. I either get nothing or hundreds of false hits.
Any help would be appreciated please.
Regards.

**Comment by speedyrazor** [comment]
Hmmm, you've discovered that I am a complete nube when it comes to this stuff :)
OK, I have a NodeMCU D1 (not played with that yet), are you saying to continue to use the Sonoff Basic for the lights and then the D1 for the sensors, or use the D1 for the switch (add a relay) and the 3 sensors?

**Comment by Jason2866** [comment]
Switch the light (if powered from AC mains) with the sonoff.
For all the other things the NodeMCU is a perfect choice.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered and the issue was just not enough energy from power supply. If you need further assistant please find us in the Tasmota Chat. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
