### ISSUE TITLE
Alexa can't discover the device

### ISSUE THREAD

**Issue by mohaggag** [arendst/Sonoff-Tasmota#534]
hue bridge is working with one device only every time i ask alexa to discover my devices it only discover one device and switch between them , it can see all but only choose  one devices randomly

**Comment by citrusfizz** [comment]
are you using dhcp or static ips?
kinda sounds like your sonoffs have the same IP or some kinda weird netmask settings. if they are taking turns showing up in the Alexa app, 
heres a few things to try:

- make sure the IPs are different and your netmask is correct. 
- make sure the friendly name is different. which i assume it is. but still worth mentioning. 
- also try setting the wifi host name as the same as your friendly name. 
- try disconnecting power and connecting it again instead of just restarting the sonoff
- try upgrading to the latest version of sonoff
- try rebooting the echo
