### ISSUE TITLE
Two lines 1-ware for temperature sensor with multiple sensors per line

### ISSUE THREAD

**Issue by labastov** [arendst/Sonoff-Tasmota#5476]
**Have you look for this feature in other issues and in the wiki?**
yes.

**Is your feature request related to a problem? Please describe.**
I make home automatisation and have several 1-ware line with 5, 15 and 12 sensors(star topology ), I cant connection it per one line. I must have three eps8266 divices now.

**Describe the solution you'd like**
Two or three lines 1-ware for temperature sensor with multiple sensors per line. Will be 25-40 Sensors, and need make compact mqtt packet. For exsample {"Time":"2019-03-11T22:20:23","DS18x20":{"L1_SENSORS":5,"L2_SENSORS":10,"L3_SENSORS":15,"2861641276706B16":20.55, ...}}

Move this definited to  sonoff.h file
#define DS18X20_MAX_SENSORS
#define DS18X20_LINES 
#define DS18X20_SHORT_MQQT

**Comment by ascillato** [comment]
Hi, 

The request for new virtual 1-wire buses and also virtual I2C buses was asked before like in https://github.com/arendst/Sonoff-Tasmota/issues/2707

Sorry, up to now it is not supported and I don't think is going to be added soon due the increase of RAM usage for that feature, and also due to that the next Tasmota stable release is going to be with the old stable arduino core 2.3.0 (that have few free RAM). The core selection was done to provide a more stable wifi/mqtt environment for Tasmota users until the next optimized arduino core is released by the ESP8266 Arduino Group. They are working hard on that.

Adding the label **Feature Request (hold over)** to be taken into account in the future. 

Thanks for sharing your ideas.
