### ISSUE TITLE
Request: add ability to calibrate white colour on RGB LED instances

### ISSUE THREAD

**Issue by dave-sausages** [arendst/Sonoff-Tasmota#5479]
I have a 30w LED floodlight which I put a Magichome module in flashed with Tasmota.

It all works fine, but the red channel appears to be brighter than the other 2 channels (which is strange given it already has the resistors in line with it from the original control board).

I can't see anyway to calibrate or adjust the red channel to reduce it and bring it inline with the blue and green ones. I can find commands to adjust the global pwm range, but not just for the one pwm channel.

**Comment by ascillato** [comment]
Please, try command LEDTABLE 1 to see if that makes a better color behaviour in your led

**Comment by ascillato** [comment]
Also please complete the troubleshooting template and please, post a picture of your led.

It is juat a 3 channel led ?

**Comment by ascillato2** [comment]
Please, could you be so kind on completing the troubleshooting template in order to have more information so as to properly help you?

Also, please post a picture of your led. It is a 3 channel led? 

Have you tried to use the console command `ledtable 1` to see if that makes a better color behaviour in your led? 

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Closing this issue as there isn't feedback. Please, when you have time, share the requested information. Thanks.
