### ISSUE TITLE
Add support for Robotdyn Dimmer Module

### ISSUE THREAD

**Issue by akhif4u** [arendst/Sonoff-Tasmota#5573]
**Have you look for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Connect Robotdyn Dimmer module ( https://m.banggood.in/3Pcs-RobotDyn-AC-Light-Dimmer-Module-For-PWM-Control-1-Channel-3_3V5V-Logic-AC-50hz-60hz-220V-110V-p-1255783.html?rmmds=myorder&cur_warehouse=CN ) which uses zero cross detection with mqtt support for dimming

**Describe alternatives you've considered**
The module works with wemos d1 mini using this library https://github.com/RobotDynOfficial/RBDDimmer . But without the benefits of tasmota its nothing.

**Additional context**

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Please read https://github.com/arendst/Sonoff-Tasmota/blob/master/CONTRIBUTING.md
You are welcome to contribute the needed driver.

**Comment by ascillato** [comment]
@akhif4u

Hi,

Sorry, this issue is duplicated. It has been long discussed this module.

There is an issue that makes very difficult to support it on Tasmota. It requires the Esp8266 to be real time (or very close to it) so as to correctly manage the ZCD (zero crossing detector. Tasmota is not real time due it is supporting a lot of sensors and protocols. So the manage in real time of ZCD is not going to be efficient and the dimming will be really bad. 

So, I'm sorry to say but that type of dimmer module is not supported and not going to be supported.

A working solution for use that dimmer (as other commercial products also do) is to have a separate MCU to manage the ZCD and the dimmimg function. So you can do the dimmer with another arduino or esp8266 with the code you provided and control that device from serial from Tasmota. Using in that way, Tasmota will work using the actual codebase and the rules feature.

Hope this helps.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
