### ISSUE TITLE
My Tuya plug restarts randomly

### ISSUE THREAD

**Issue by vaidyasr** [arendst/Sonoff-Tasmota#5626]
I have successfully flashed the Tasmota on my Tuya smart plug. But the plug is switched off randomly. I have checked the settings and PowerOnState is 3 and ButtonRetain is off and SwitchRetain is off only. I can't find any useful info in console. How do I fix it?. 
I have seen the plug is switched off whenever the Wifi is disconnected.
The plug is [here](https://www.aliexpress.com/item/US-Standard-Mini-Smart-Wifi-Socket-Remote-Control-Power-Strip-Timing-Switch-for-Smart-Home-Automation/32969667372.html?spm=a2g0s.9042311.0.0.1b134c4dmKc1iK).

**Comment by Jason2866** [comment]
Issue template is missing. Status 0....

**Comment by ascillato2** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
