### ISSUE TITLE
Reset wemos instead of reflashing

### ISSUE THREAD

**Issue by agoralive** [arendst/Sonoff-Tasmota#5645]
As the subject describes, I am searching for at way to reset a wemos running the Tasmota software, without having to reflash the entire thing?

On a sonoff unit this is done by pressing the on/off button 3 or 4 times, could this be implanted into the wemos as well?

**Comment by ascillato** [comment]
Hi,

As the troubleshooting template is missing, there is a lot of information on your issue that we don't know. 
If what you want is to push the button of the wemos for 40 seconds to reset all settings, you previously need to define in the the Tasmota webUI the gpio of the physical button as button1.

In the sonoff basic works as soon as you flash it, because the default module for Tasmota is sonoff basic. In your case, you need to change the module to generic and set the gpios as you need.

There is no way for the software to automatically detects which device you have and set the gpios for you. Sorry. 

If you need further assistant, please find us in the Tasmota support chat.

Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
