### ISSUE TITLE
How to fulfill MQTT Homie Convention manually

### ISSUE THREAD

**Issue by alwashe** [arendst/Sonoff-Tasmota#5824]
It would be awesome if the [MQTT Homie Convention] (https://homieiot.github.io/specification/) is included in Tasmota.

Is it possible to fulfill the MQTT homie specification manually?

referring to: https://github.com/arendst/Sonoff-Tasmota/issues/4696

**Comment by Jason2866** [comment]
Dont open a new issue since the question has been answered in #4696
There will be no support if no PR is provided for review.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
