### ISSUE TITLE
Enhancement of the color command (RGBW)

### ISSUE THREAD

**Issue by Vujagig** [arendst/Sonoff-Tasmota#5895]
**Have you look for this feature in other issues and in the wiki?**
yes

**Is your feature request related to a problem? Please describe.**
The real white of a SL6812 RGBW LED can not be controlled with the color 12 (rgb white) command

**Describe the solution you'd like**
An enhancement of the color command:
color 13 (using the real white: 000000FF)
color 14 (using the rgb & real white: FFFFFFFF)
If possible, control via alexa to the new colors

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato** [comment]
Hi, sorry. There is no enough information. Please, use the troubleshooting template with status 0 output and the console output when this happens to you. Also, remember to have weblog set to 4 as the troubleshooting template ask for. Thanks

**Comment by meingraham** [comment]
`color 12 (rgb white) command` - works in Africa ;-)

**Comment by Jason2866** [comment]
Use latest dev version. This issues is solved with PR #5878

**Comment by s-hadinger** [comment]
I have on my todo list a way to mix RGB and White seamlessly. Stay tuned.

**Comment by ascillato2** [comment]
@s-hadinger Cool!!! Thanks.
