### ISSUE TITLE
Switch state

### ISSUE THREAD

**Issue by hernanjc** [arendst/Sonoff-Tasmota#6024]
Hi,

I have several shelly 1 devices connected to wall switches and everything integrated with Home Assistant. Everything works: Shelly 1 devices send a MQTT message (stat/shellyX/POWER ON/OFF) everytime output relay is toggles.  However I would like home assistant to be able to detect if the switch has been pressed: I'd like to perform different actions if the wall switch is toggled and if the output is changed via Home Assistant.

I've been reading MQTT documentation and the only possible solution that I've found is setting SwitchTopic to 1 so Shelly devices send a cmnd/shellyX/power1 comand only when wall switch is pressed. However I don't know how to manage it whit home assistant as this is a command message and not a status message. 

In the same way MQTT sends a stat/shellyX/POWER message everytime output changes it'd be usefull it sends a message everytime SW input changes, something like stat/shellyX/SWITCH.

Thank you!

**Comment by Jason2866** [comment]
Sorry i didnt get it where the issue is in Tasmota. If it is a question how to configure HA
please ask in HA Discord.

If you have questions to Tasmota please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
