### ISSUE TITLE
Sonoff Pow R2, all values displays 0

### ISSUE THREAD

**Issue by aerisk** [arendst/Sonoff-Tasmota#6041]
Greetings, 

I have a problem with the Tasmota Firmware which I cannot get the power display correctly. I use Sonoff Pow R2 to monitor the power of my device but it seems that the power, voltage, current and energy only shows 0 result. The toggle button seems to work fine. I already try changed the configuration of the module to Sonoff Pow R2, Sonoff Pow but it still does not work. 

I have connected to MQTT and it works fine, except for the sensor.

MQTT respond (Received Messages):
tele/sonoff/LWT | Online
-- | --
tele/sonoff/LWT | Online
cmnd/sonoff/POWER |  
tele/sonoff/INFO1 | {"Module":"Sonoff Pow R2","Version":"6.5.0(release-sonoff)","FallbackTopic":"cmnd/DVES_CA525E_fb/","GroupTopic":"sonoffs"}
tele/sonoff/INFO2 | {"WebServerMode":"Admin","Hostname":"sonoff-4702","IPAddress":"192.168.1.127"}
tele/sonoff/INFO3 | {"RestartReason":"Software/System restart"}
stat/sonoff/RESULT | {"POWER":"OFF"}
stat/sonoff/POWER | OFF
tele/sonoff/STATE | {"Time":"2019-07-08T03:55:25","Uptime":"0T00:00:14","Vcc":3.174,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"dd-wrt","BSSId":"F8:D1:11:7E:D0:38","Channel":1,"RSSI":76,"LinkCount":1,"Downtime":"0T00:00:04"}}
domoticz/in | {"idx":1,"nvalue":0,"svalue":"0.000","Battery":55,"RSSI":7}
tele/sonoff/SENSOR | {"Time":"2019-07-08T03:55:26","ENERGY":{"TotalStartTime":"2019-07-05T10:00:09","Total":0.000,"Yesterday":0.000,"Today":0.000,"Period":0,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}

![Sonoff Pow R2 tasmota error 1](https://user-images.githubusercontent.com/52641043/60780013-620d6e80-a16f-11e9-8919-cc6c52c07394.PNG)

![Sonoff Pow R2 tasmota error 2 (ON)](https://user-images.githubusercontent.com/52641043/60780030-6e91c700-a16f-11e9-97ad-525ccf07877e.PNG)

Right now, I only want the monitoring result to be working.

**Comment by ascillato2** [comment]
Hi, 

Sorry, a lot of information is missing. You forgot to follow the troubleshooting template. 

Have you search in other issues?

Have you set seriallog to 0?

Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
