### ISSUE TITLE
PIR sensor not switching shelly ?

### ISSUE THREAD

**Issue by NiekN** [arendst/Sonoff-Tasmota#6168]
I have a PIR sensor which switched some light 230VAC,
So i thought i would like to see it status , if it is ON or OFF, or switch it manually 
I have already a shelly with tasmota v6.5.0, and is running fine

so a added a new shelly (with also tasmota v6.5.0)  between the PIR and lights..
Now i can switch it manually(webinterface)..  i connected the output of the PIR sensor (230VAC)
with the shelly (SW connection).  i can hear when this PIR is switching  but the shelly does not react??????

i checked the voltage on they  SW connection .  when PIR is active it is 230VAC.  When PIR is not active , it is something around 123VAC....  there is a voltage standard on the SW connection at shelly 

i double check the connections , and also check a new shelly (with standard shelly firmware)) . When only connecting the 230VAC power connection(L and N) , this 123VAC is present , so that looks normal ..

The only difference between normal connections(behind a switch in the wall) and my circuit , is that the cable between the PIR sensor and the shelly (SW connection) is about 7meter long ..  is that a problem ?

maybe the shelly does not see the EDGE trigger anymore because the cable is to long ( is it reacting on a edge or ?????) 

When using a jumper from L to SW connection, i hear the shelly switching..  so it looks the shelly is working OK    

can somebody help in this ??    or can i change button type   ?????

**Comment by meingraham** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the template with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
