### ISSUE TITLE
Adafruit MQTT (AIO) - can't connect

### ISSUE THREAD

**Issue by m-jurczyszyn** [arendst/Sonoff-Tasmota#6237]
Hi!
Let me just say that TASMOTA is a blessing for my sonoff devices, and I love it. 

I'm using latest pre-compiled 6.6 and my Sonoff Basic fails to connect to Adafruit IO.
CONSOLE OUTPUT HERE:
```
22:28:13 WIF: Checking connection...
22:28:13 WIF: Connected
22:28:20 MQT: Attempting connection...
22:28:20 MQT: Connected
22:28:20 MQT: tele/termometr/LWT = Online (retained)
22:28:20 RSL: cmnd/termometr/POWER = 
22:28:20 MQT: Subscribe to cmnd/termometr/#
22:28:20 MQT: Subscribe to cmnd/sonoffs/#
22:28:20 MQT: Subscribe to cmnd/DVES_xxxxxxx_fb/#
22:28:21 MQT: Attempting connection...
22:28:21 MQT: Connect failed to io.adafruit.com:1883, rc 7. Retry in 10 sec
```

STATUS 0 OUTPUT HERE:
```
22:29:22 RSL: stat/termometr/STATUS = {"Status":{"Module":1,"FriendlyName":["Termometr"],"Topic":"termometr","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
22:29:22 RSL: stat/termometr/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:03:48","StartupUTC":"2019-08-15T20:25:34","Sleep":50,"CfgHolder":4617,"BootCount":41,"SaveCount":133,"SaveAddress":"FA000"}}
22:29:22 RSL: stat/termometr/STATUS2 = {"StatusFWR":{"Version":"6.6.0(release-sonoff)","BuildDateTime":"2019-07-06T13:10:20","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
22:29:22 RSL: stat/termometr/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["YR-SGS4m",""],"TelePeriod":120,"Resolution":"558180C0","SetOption":["0000800B","280500000100060000000000000000000000","00000000"]}}
22:29:22 RSL: stat/termometr/STATUS4 = {"StatusMEM":{"ProgramSize":503,"Free":500,"Heap":13,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","0FDAE396","001783A0","22B617CD","01003BC0"]}}
22:29:22 RSL: stat/termometr/STATUS5 = {"StatusNET":{"Hostname":"termometr","IPAddress":"192.168.43.160","Gateway":"192.168.43.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.43.1","Mac":"84:F3:EB:A7:4A:FB","Webserver":2,"WifiConfig":2}}
22:29:22 RSL: stat/termometr/STATUS6 = {"StatusMQT":{"MqttHost":"io.adafruit.com","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A74AFB","MqttUser":"mjr_crash","MqttCount":19,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
22:29:22 RSL: stat/termometr/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 15 20:29:22 2019","Local":"Thu Aug 15 22:29:22 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+02:00","Sunrise":"06:42","Sunset":"21:06"}}
22:29:22 RSL: stat/termometr/STATUS10 = {"StatusSNS":{"Time":"2019-08-15T22:29:22","DS18B20":{"Temperature":24.4},"TempUnit":"C"}}
22:29:22 RSL: stat/termometr/STATUS11 = {"StatusSTS":{"Time":"2019-08-15T22:29:22","Uptime":"0T00:03:48","Heap":13,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":1,"SSId":"removed","BSSId":"removed:F6:98:C2","Channel":1,"RSSI":76,"LinkCount":1,"Downtime":"0T00:00:12"}}}
```

I double checked the server url, port, username and AIO key.
Adafruit connection details:
> Host | io.adafruit.com
> Insecure Port | 1883
> Username | Your Adafruit IO Username
> Password | Your Adafruit IO Key

Device connects to _CloudMQTT_ just fine.
I've read the previous issues regarding Adafruit IO, checked the forum and discord chat but the answer isn't there. Could anyone confirm, that Adafruit IO is working?
The AIO key is 32 characters in length.

**Comment by ascillato2** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato** [comment]
Anyway, a public MQTT server is not recommended due to it is very easy to hack and take control of your devices, replace the firmware of your devices and take control of your network.

That is why Tasmota is designed to be used in a local network. There are plenty of home automation software options in the wiki.

**Comment by ascillato** [comment]
you can try modifying the max amount of available characters for the password

https://github.com/arendst/Sonoff-Tasmota/blob/6d5ffdf068669c0f6b04bcb3656f53a478440b4c/sonoff/settings.h#L222

and compile by yourself

Remember that modifying the settings memory makes Tasmota not being backwards compatible, so you will need to erase all flash and flash your custom version.

**Comment by m-jurczyszyn** [comment]
Does the 33 in the brackets mean it's current length is 33 chars?

**Comment by s-hadinger** [comment]
As it is a C string the last byte is zero so you have only 32 characters available.

**Comment by ascillato2** [comment]
Hi, any news on this?

**Comment by m-jurczyszyn** [comment]
I can confirm, that the problem was in the topic. Adafruit is very specific when it comes to the MQTT topic:
> Any one of the following topic forms is valid for a feed:
>     (username)/feeds/(feed name or key)
>     (username)/f/(feed name or key)

I'm still having issues subscribing/ publishing to specific feed. Currently testing various configurations.

**Comment by m-jurczyszyn** [comment]
Why does tasmota try to subscribe to topic ending with /cmnd/ ?

**Comment by meingraham** [comment]
@m-jurczyszyn 

Have you set Home Assistant auto-discovery [`SetOption19`](../wiki/Commands#setoption19)? This [changes the structure of Tasmota topics](../wiki/Home-Assistant#warning-important).

The topic structure will be `%topic%/cmnd/+`  rather than the default `cmnd/%topic%/+`

Our ability to provide assistance is __greatly__ hampered since you did not take a few minutes to complete the  [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please close this issue and address any further questions to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Great to know that now you could connect to the broker.

If you need further assistance on configuring, please address this to the Tasmota support chat.

Anyway, I still not recommending a public MQTT broker with insecure ports. Those are very easy to hack, take control of your devices and do an OTA and change the firmware off all your devices and control all your network. Really not recommended.

**Comment by tech-freak** [comment]
> I can confirm, that the problem was in the topic. Adafruit is very specific when it comes to the MQTT topic:

hi there
any update on this ?
