### ISSUE TITLE
Blitzwolf BW-SHP5 flashing issue

### ISSUE THREAD

**Issue by denxhun** [arendst/Sonoff-Tasmota#6315]
### ISSUE DESCRIPTION - TROUBLESHOOTING
I've tried to flash a Blitzwolf BW-SHP5 device with the precompiled sonoff-basic.bin v6.6.0. Unfortunately the device is not responding, when I plug into the power outlet the blue led flashes once and nothing else. No serial output nor wifi AP appears. The flashing process went well (3 times):
```
esptool.py v2.6
Serial port COM3
Connecting....
Detecting chip type... ESP8266
Chip is ESP8285
Features: WiFi, Embedded Flash
MAC: 2c:f4:32:XX:XX:XX
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.9s
Flash params set to 0x0220
Compressed 432432 bytes to 300963...
Wrote 432432 bytes (300963 compressed) at 0x00000000 in 26.8 seconds (effective 129.2 kbit/s)...
File  md5: 6e3f2a8b357f0a986d4d85992784ba5e
Flash md5: a00fe13af1171b221a47a657186de4c1
MD5 of 0xFF is d30a343ba436b7c173c9415fe691fd03
```
(mac address masked manually)

### REQUESTED INFORMATION
Maybe I missed someting and have to do something differently so please help me out.
I'm using Windows 10, NomdeMCU PyFlasher, CP2102 USB-UART with 3.3V power.
I read that this device should work based on issue #5756 

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : Blitzwolf BW-SHP5
- [x] Tasmota binary firmware version number used : v6.6.0 / pre-compiled 
- [ ] Development IDE - Compiler / Upload tools used : ____ / ____
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:


```
- [ ] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:


```
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by curzon01** [comment]
From issue template guide:

Please **DO NOT OPEN AN ISSUE**:
  _If your issue is a flashing issue, please address that to the Tasmota Support Chat_

Anyway, sonoff.bin ist the recommended binary, not sonoff-basic.bin - see https://github.com/arendst/Sonoff-Tasmota/releases

Please address this to [Support's Community](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md#supports-community).
The community channels are a better and more dynamic for helping you.
Github issues are mainly used for Tasmota software feature requests and bug reporting. 

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

<hr>

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
