### ISSUE TITLE
Flashing a New Generation SONOFF RF With ESP8255

### ISSUE THREAD

**Issue by ilmisu** [arendst/Sonoff-Tasmota#6365]
Hi everyone, 

Im' trying since days to flash tasmota on a SonoffRF Module based on ESP8285 Chip. (that's what arduino says...)
I flash it with this setup: 
![Immagine](https://user-images.githubusercontent.com/50550633/64448786-c81a6180-d0de-11e9-891b-afe4b5d90aab.png)

I can compile and upload the project, and by serial monitor I obtain This:

![Cattura](https://user-images.githubusercontent.com/50550633/64448848-e2ecd600-d0de-11e9-9da7-f41e285739d7.PNG)

what Can I do, may I waste it onto the trash? it is in a loop, and nothing starts.

Thanks in advance for help.
Bye!

**Comment by meingraham** [comment]
`<If your issue is a flashing issue, please address that to the Tasmota Support Chat>`

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
