### ISSUE TITLE
Regarding the recent SDM120 development

### ISSUE THREAD

**Issue by gajotnt** [arendst/Sonoff-Tasmota#6417]
>  * Add driver USE_SDM120_2 with Domoticz P1 Smart Meter functionality as future replacement for USE_SDM120 - Pls test and report

Have been using this for a couple of days, gives me really wront values on the daily usage.
Please dont replace, if you can keep has is, using the SDM similar to POW.

The return values are within what is expected (compare with WASTE) but the usage is way, way off.
![sdm](https://user-images.githubusercontent.com/25504364/64893104-c8c67100-d665-11e9-868a-d10c5bfd16f7.JPG)

Maybe i configured something wrong, did not change any of the Tariff comands. Because the Usage 1 in domoticz is always @ 0watts and only Usage 2 is registring values.

![last-5-days](https://user-images.githubusercontent.com/25504364/64893122-d4199c80-d665-11e9-8a1d-b154ebf9281a.jpeg)
![Usage 1 only](https://user-images.githubusercontent.com/25504364/64893121-d4199c80-d665-11e9-9864-0c645effc9b9.jpeg)
![Usage 2 only](https://user-images.githubusercontent.com/25504364/64894258-c0bc0080-d668-11e9-80b3-f20a67896557.jpeg)

**Comment by arendst** [comment]
Partly answering:
- Domoticz Usage1 is energy usage during tariff1 period.
- Domoticz Usage2 is energy usage during tariff2 period.

As you did not change the Tasmota tariff settings from the default settings there are no tariffs in use and only Usage2 will report values being the Peak period as defined by Domoticz:

![image](https://user-images.githubusercontent.com/11044339/64906832-526c5200-d6eb-11e9-94f1-e717f0a740a6.png)

In the above case tariff is defined as ``{"Tariff":{"Off-Peak":[23,22],"Standard":[7,6],"Weekend":"ON"}}`` so that should explain your Usage question.

**Comment by gajotnt** [comment]
Ok thanks for the input, will configure the tariffs time period and report back later.

**Comment by ascillato2** [comment]
Adding the label On Hold until the user has time to test.
