### ISSUE TITLE
add unique name to MQTT Message send by RF Bridge

### ISSUE THREAD

**Issue by abhitheawesomecoder** [arendst/Sonoff-Tasmota#6482]
When Rf Bridge sends MQTT message it sends json with code Data. But I also want to give a unique device name and send it. can I add it to the json. If yes how? Is it possible using the rules?

**Comment by meingraham** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the  [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Jason2866** [comment]
No not possible, and why it is needed? The device is recognized by its rf Data
`MQT: tele/sonoff-8E8329/RESULT = {"Time":"2019-09-24T13:40:33","RfReceived":{"Sync":11310,"Low":380,"High":1100,"Data":"150554","RfKey":"None"}}`
Device naming can and should be done in a Home Automation Hub.
ESP simply has to less flash space for doing such things. Doing this would result in loosing features.
So it will NOT implemented.

**Comment by abhitheawesomecoder** [comment]
RF bridge is simply forwarding the data received from rf device to mqtt but
how will server recognise which RF bridge is sending the data?

**Comment by Jason2866** [comment]
@abhitheawesomecoder  Every Tasmota device has a unique name (topic). 
In my exampe it is `sonoff-8E8329`
Take you time and read in wiki all about mqtt.

**Comment by abhitheawesomecoder** [comment]
Any clue on how to write the rule. I mean when RF data and codes are
received by RF bridge how to access it so that it can be published?

**Comment by meingraham** [comment]
Rule trigger example... from the wiki: `RfReceived#Data=0xE8329E`

`Take you time and read in wiki`

**Comment by meingraham** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/6482#issuecomment-534528947

`But then, are all codes sent from RF device unique?`

**Comment by digiblur** [comment]
I use this rule and then have NodeRed break down all my decisions from there.

on rfreceived#Data do publish rfBridge/all %value% endon

**Comment by Jason2866** [comment]
If a rf device transmits a code and you have more than one RfBridge **the received RF data will be the
same on ALL RFBridges**. You can recognize every Bridge with his unique topic result.
Case closed :-)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
