### ISSUE TITLE
Strange switch behavior from Sonoff 4ch Pro

### ISSUE THREAD

**Issue by bwze** [arendst/Sonoff-Tasmota#6549]
I accidentally pressed one of the switches on my 4ch Pro twice in quick succession and then it wouldn't react to presses anymore. 

I had to power cycle the device to get the switch to react to presses properly again.

This happens to all switches and will occur if quickly pressing the button with the associated relay either active or inactive.

The switches appear to latch themselves high and won't unlatch.

If a switch is latched and I double click another switch, the first switch will release and the second switch will become unresponsive.

Has anyone else experienced this and if so, is it considered a normal behavior?

Sonoff 4ch Pro v1.1
Tasmota v6.6.0

**Comment by meingraham** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the  [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
