### ISSUE TITLE
Problem: lost wifi and connect - shutters are closing...

### ISSUE THREAD

**Issue by MaN093** [arendst/Sonoff-Tasmota#6572]
Hi,

I have a problem with my sonoff dual loose connection (wifi).

Indeed, when it connects to the wifi again, my shutters are closing.
In the console of my sonoff : 

"10:24:23 MQT: Tentative de connexion...
10:24:23 MQT: Connecté
10:24:23 MQT: tele/sonoff_Gabriel/LWT = Connecté (persistant)
10:24:23 MQT: cmnd/sonoff_Gabriel/POWER = 
10:24:24 MQT: stat/sonoff_Gabriel/RESULT = {"POWER2":"ON"}
10:24:24 MQT: stat/sonoff_Gabriel/POWER2 = ON
10:24:24 MQT: stat/sonoff_Gabriel/RESULT = {"POWER2":"OFF"}
10:24:24 MQT: stat/sonoff_Gabriel/POWER2 = OFF
10:24:24 MQT: stat/sonoff_Gabriel/RESULT = {"POWER1":"ON"}
10:24:24 MQT: stat/sonoff_Gabriel/POWER1 = ON
10:24:24 MQT: stat/sonoff_Gabriel/RESULT = {"POWER1":"OFF"}
10:24:24 MQT: stat/sonoff_Gabriel/POWER1 = OFF
10:24:24 MQT: stat/sonoff_Gabriel/RESULT = {"POWER2":"ON"}
10:24:24 MQT: stat/sonoff_Gabriel/POWER2 = ON
10:24:42 MQT: stat/sonoff_Gabriel/RESULT = {"POWER2":"OFF"}
10:24:42 MQT: stat/sonoff_Gabriel/POWER2 = OFF"

Any suggestions ? I wish that when the wifi reconnects, that no relay is activated ...

Thanks for help.

**Comment by Jason2866** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.
 
Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).
 
Thanks.
 
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
