### ISSUE TITLE
Issue with WiFi Manager when adding parameters to settings.h

### ISSUE THREAD

**Issue by Thierry1970** [arendst/Sonoff-Tasmota#6592]
Hello,
I am tring to modify timeprop branch to store some of its settings in the SYSCFG structure settings.
I am adding the following at the end of SYSCFG struct :
...
  uint32_t      cfg_timestamp;             // FF8
  uint32_t      cfg_crc32;                 // FFC
#ifdef USE_TIMEPROP
  float Timeprop_FallBackPowers[TIMEPROP_NUM_OUTPUTS];
  int Timeprop_Cycles[TIMEPROP_NUM_OUTPUTS];
  int Timeprop_MaxIntervals[TIMEPROP_NUM_OUTPUTS];
#endif
} Settings;

In my_user_config.h, I have :
#define TIMEPROP_NUM_OUTPUTS          1 

When I compile with Tasmota 6.6.0.15, the Wifi Manager refuses to work when if I add one of those lines : it acts as if saving is not working anymore, not connecting to wifi and endlessly coming back to the wifi config Web Page. If I suppress the 3 lines, config manager works correctly.

Any idea to help ?
Is there a better way to store some settings parameters for custom function ?

Thierry

**Comment by andrethomas** [comment]
> Any idea to help ?

Cannot be done in the way you're doing it.

> Is there a better way to store some settings parameters for custom function ?

Take a look at Issue #5081 for reference and then refer to the ESP8266 Arduino Core documentation for more information.

**Comment by andrethomas2** [comment]
Please note that GitHub Issues are for reporting bugs and requesting additional features.

Please search the Wiki for the information you require or visit Discord Chat where general questions and answers are handled.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Thierry1970** [comment]
Thanks for your kind answer andrethomas2.
I confirm I read the wiki, and it says : "Variables can be appended to struct SYSCFG {} Settings in file sonoff/settings.h"
Wiki Page : https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API.

So I really cannot figure out what turns wrong.
Is the struct SYSCFG already at its maximum size ?

**Comment by arendst** [comment]
That's obsolete as the safe area has been expanded tot he full 4k flash page recently. So you will have to store your settings before cfg_timestamp and carefully calculate to get the total of 4096 bytes max.

Happy programming.

**Comment by Thierry1970** [comment]
Hi Theo, congratulation for your work and thanks a lot for your answer !

**Comment by andrethomas** [comment]
The problem is with `#define TIMEPROP_NUM_OUTPUTS 1` insofar that it will cause the `SYSCFG` structure to be a specific size - Assuming you want to change this between compiles you will get a different size for the `SYSCFG` depending on how many `TIMEPROP_NUM_OUTPUTS` you are using.

What I suggest you do is figure out how many you need as a maximum (even if there are those which you will not use all the time) and pre-define them as arrays in the `SYSCFG` structure.

What @arendst means is that you need to look at the `uint8_t       free_e90[360];` line which is 360 bytes long and see how many bytes you need for your additional data... then insert your desired variables into the structure before the 360 bytes and remove the bytes used by your structure from the free_e90 declaration. So if your data needs 100 bytes then free_e90 would become [260] etc.

Perhaps better could be to add it between the free_e90 and the `cfg_timestamp` - This would give you a better chance of maintaining sanity between upgrades.

If this is not possible the other alternative is to follow the method of creating your own struct and writing it somewhere to an unused area of flash - This may also make it easier to integrate into the custom driver you're thinking of making and make it easier to keep your code up to date from the development branch.
