### ISSUE TITLE
Sonoff Dual

### ISSUE THREAD

**Issue by Mark-Greek** [arendst/Sonoff-Tasmota#6595]
Hi
i have a Sonoff Dual Version 6.6.0, the double Toggle functioned

![2019-10-08 19_17_30-Window](https://user-images.githubusercontent.com/35305385/66417473-59dbfe00-ea00-11e9-8ae9-fd581d6282d3.png)

but i install the Version 6.6.016 and both were gone

![2019-10-08 19_12_58-Window](https://user-images.githubusercontent.com/35305385/66417412-3618b800-ea00-11e9-987e-e207a6f2ecc2.png)

![2019-10-08 19_22_17-Window](https://user-images.githubusercontent.com/35305385/66417821-1b930e80-ea01-11e9-90fa-13b4dda87c82.png)

**Comment by meingraham** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the  [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
