### ISSUE TITLE
Add commands for settings to templates

### ISSUE THREAD

**Issue by DSuds** [arendst/Sonoff-Tasmota#6607]
**Templates are almost great**
But for many of the devices that need them additional setup is required after loading a template.  This can be executing commands like "SetOption34 57" or "LEDTable 0" to ensure correct operation or just convenience commands like "SetOption19 True" enable consistent deployments in a specific environment.

Adding an "exec" section to the templates would allow a set of commands to be executed when loading a template.  I'm not sure what constraints are on the template string or how it is managed so there is possibly a better implementation path.

**Comment by meingraham** [comment]
This was discussed in an earlier topic (i.e., this is a duplicated issue).

Net-net, it's not planned because it is simple to include a `Backlog` of the necessary setup commands in the Template note. Yes, not all contributors have taken this step, but with an open collaborative environment, it is nearly impossible to "regulate" that. There are nearly 500 templates which represents almost as many different contributors. In addition, each situation is slightly different (device characteristics, user preferences, etc.).  `SetOption19` is a perfect example - that only applies to Home Assistant users.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by DSuds** [comment]
Sorry I didn't see the previous issue! 
While I agree items like SetOption 19 are clearly not universal other settings are absolutely necessary for correct operation and in those cases templates fail to configure devices.  If the goal of templates is to 'Configure most things, most of the time" so be it.

**Comment by meingraham** [comment]
>  If the goal of templates is to 'Configure most things, most of the time" so be it.

Yup, that's exactly what the goal was when architecting a solution that allows 500 devices to run Tasmota.
