### ISSUE TITLE
Planned support for S30

### ISSUE THREAD

**Issue by vcazan** [arendst/Sonoff-Tasmota#724]
Want to buy the S30 unit but see it is not supported. Any plans on supporting this device?

**Comment by arendst** [comment]
Not yet but if you can provide information regarding internal connections to button and relay it should be easy to do.

It's currently only available in US version (110V).

**Comment by JonSilver** [comment]
I believe these are Itead S30 UK model:
https://www.amazon.co.uk/MEAMOR-Wireless-Function-Required-Anywhere/dp/B0743BLH3G/

**Comment by bobmoran00** [comment]
I have opened one up, S30 US version.  Glued case, 8285,  four pin holes labled vcc D+ D- Grd.  were no help.
Used the four holes at J1  J1=vcc, next=Tx, next=rx next(boxed)=grd.  I was able to flash blink with these as a test.  Still testing.
The unit is similar to the Amazon refrence but no USB port but that is probable what Vcc,D+D-&grd are for.

**Comment by bobmoran00** [comment]
Turns out the USB is a Charging only port D+ & D- go nowhere.

**Comment by mrubli** [comment]
For reference below are some photos of a destructive S30 teardown. As bobmoran00 pointed out J1 exposes the 8285's `EXT_RSTB`, `U0TXD`, `U0RXD` pins and ground. The unpopulated USB port is simply for power since `D+` and `D-` are tied together.

![20210130_160159](https://user-images.githubusercontent.com/29906522/106374452-9d5d3700-63be-11eb-94ea-7a521dcb7e83.jpg)
![20210130_160256](https://user-images.githubusercontent.com/29906522/106374453-a0582780-63be-11eb-98df-fbf50c749722.jpg)
![20210131_114757b](https://user-images.githubusercontent.com/29906522/106374828-89ff9b00-63c1-11eb-84ac-18c531bcf2c1.jpg)
